/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AddRulesRequest,
    instanceOfAddRulesRequest,
    AddRulesRequestFromJSON,
    AddRulesRequestFromJSONTyped,
    AddRulesRequestToJSON,
} from './AddRulesRequest';
import {
    DeleteRulesRequest,
    instanceOfDeleteRulesRequest,
    DeleteRulesRequestFromJSON,
    DeleteRulesRequestFromJSONTyped,
    DeleteRulesRequestToJSON,
} from './DeleteRulesRequest';

/**
 * @type AddOrDeleteRulesRequest
 * 
 * @export
 */
export type AddOrDeleteRulesRequest = AddRulesRequest | DeleteRulesRequest;

export function AddOrDeleteRulesRequestFromJSON(json: any): AddOrDeleteRulesRequest {
    return AddOrDeleteRulesRequestFromJSONTyped(json, false);
}

export function AddOrDeleteRulesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddOrDeleteRulesRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...AddRulesRequestFromJSONTyped(json, true), ...DeleteRulesRequestFromJSONTyped(json, true) };
}

export function AddOrDeleteRulesRequestToJSON(value?: AddOrDeleteRulesRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfAddRulesRequest(value)) {
        return AddRulesRequestToJSON(value as AddRulesRequest);
    }
    if (instanceOfDeleteRulesRequest(value)) {
        return DeleteRulesRequestToJSON(value as DeleteRulesRequest);
    }

    return {};
}

