/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RuleNoId } from './RuleNoId';
import {
    RuleNoIdFromJSON,
    RuleNoIdFromJSONTyped,
    RuleNoIdToJSON,
} from './RuleNoId';

/**
 * A request to add a user-specified stream filtering rule.
 * @export
 * @interface AddRulesRequest
 */
export interface AddRulesRequest {
    /**
     * 
     * @type {Array<RuleNoId>}
     * @memberof AddRulesRequest
     */
    add: Array<RuleNoId>;
}

/**
 * Check if a given object implements the AddRulesRequest interface.
 */
export function instanceOfAddRulesRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "add" in value;

    return isInstance;
}

export function AddRulesRequestFromJSON(json: any): AddRulesRequest {
    return AddRulesRequestFromJSONTyped(json, false);
}

export function AddRulesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddRulesRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'add': ((json['add'] as Array<any>).map(RuleNoIdFromJSON)),
    };
}

export function AddRulesRequestToJSON(value?: AddRulesRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'add': ((value.add as Array<any>).map(RuleNoIdToJSON)),
    };
}

