/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AnimatedGifAllOf } from './AnimatedGifAllOf';
import {
    AnimatedGifAllOfFromJSON,
    AnimatedGifAllOfFromJSONTyped,
    AnimatedGifAllOfToJSON,
} from './AnimatedGifAllOf';
import type { Media } from './Media';
import {
    MediaFromJSON,
    MediaFromJSONTyped,
    MediaToJSON,
} from './Media';
import type { Variant } from './Variant';
import {
    VariantFromJSON,
    VariantFromJSONTyped,
    VariantToJSON,
} from './Variant';

/**
 * 
 * @export
 * @interface AnimatedGif
 */
export interface AnimatedGif extends Media {
    /**
     * 
     * @type {string}
     * @memberof AnimatedGif
     */
    previewImageUrl?: string;
    /**
     * An array of all available variants of the media.
     * @type {Array<Variant>}
     * @memberof AnimatedGif
     */
    variants?: Array<Variant>;
}

/**
 * Check if a given object implements the AnimatedGif interface.
 */
export function instanceOfAnimatedGif(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AnimatedGifFromJSON(json: any): AnimatedGif {
    return AnimatedGifFromJSONTyped(json, false);
}

export function AnimatedGifFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnimatedGif {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...MediaFromJSONTyped(json, ignoreDiscriminator),
        'previewImageUrl': !exists(json, 'preview_image_url') ? undefined : json['preview_image_url'],
        'variants': !exists(json, 'variants') ? undefined : ((json['variants'] as Array<any>).map(VariantFromJSON)),
    };
}

export function AnimatedGifToJSON(value?: AnimatedGif | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...MediaToJSON(value),
        'preview_image_url': value.previewImageUrl,
        'variants': value.variants === undefined ? undefined : ((value.variants as Array<any>).map(VariantToJSON)),
    };
}

