/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockUserMutationResponseData
 */
export interface BlockUserMutationResponseData {
    /**
     * 
     * @type {boolean}
     * @memberof BlockUserMutationResponseData
     */
    blocking?: boolean;
}

/**
 * Check if a given object implements the BlockUserMutationResponseData interface.
 */
export function instanceOfBlockUserMutationResponseData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BlockUserMutationResponseDataFromJSON(json: any): BlockUserMutationResponseData {
    return BlockUserMutationResponseDataFromJSONTyped(json, false);
}

export function BlockUserMutationResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockUserMutationResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blocking': !exists(json, 'blocking') ? undefined : json['blocking'],
    };
}

export function BlockUserMutationResponseDataToJSON(value?: BlockUserMutationResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blocking': value.blocking,
    };
}

