/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Represent the portion of text recognized as a Cashtag, and its start and end position within the text.
 * @export
 * @interface CashtagFields
 */
export interface CashtagFields {
    /**
     * 
     * @type {string}
     * @memberof CashtagFields
     */
    tag: string;
}

/**
 * Check if a given object implements the CashtagFields interface.
 */
export function instanceOfCashtagFields(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tag" in value;

    return isInstance;
}

export function CashtagFieldsFromJSON(json: any): CashtagFields {
    return CashtagFieldsFromJSONTyped(json, false);
}

export function CashtagFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashtagFields {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tag': json['tag'],
    };
}

export function CashtagFieldsToJSON(value?: CashtagFields | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tag': value.tag,
    };
}

