/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CashtagFields } from './CashtagFields';
import {
    CashtagFieldsFromJSON,
    CashtagFieldsFromJSONTyped,
    CashtagFieldsToJSON,
} from './CashtagFields';
import type { EntityIndicesInclusiveExclusive } from './EntityIndicesInclusiveExclusive';
import {
    EntityIndicesInclusiveExclusiveFromJSON,
    EntityIndicesInclusiveExclusiveFromJSONTyped,
    EntityIndicesInclusiveExclusiveToJSON,
} from './EntityIndicesInclusiveExclusive';

/**
 * 
 * @export
 * @interface CashtagEntity
 */
export interface CashtagEntity {
    /**
     * Index (zero-based) at which position this entity ends.  The index is exclusive.
     * @type {number}
     * @memberof CashtagEntity
     */
    end: number;
    /**
     * Index (zero-based) at which position this entity starts.  The index is inclusive.
     * @type {number}
     * @memberof CashtagEntity
     */
    start: number;
    /**
     * 
     * @type {string}
     * @memberof CashtagEntity
     */
    tag: string;
}

/**
 * Check if a given object implements the CashtagEntity interface.
 */
export function instanceOfCashtagEntity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "end" in value;
    isInstance = isInstance && "start" in value;
    isInstance = isInstance && "tag" in value;

    return isInstance;
}

export function CashtagEntityFromJSON(json: any): CashtagEntity {
    return CashtagEntityFromJSONTyped(json, false);
}

export function CashtagEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashtagEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'end': json['end'],
        'start': json['start'],
        'tag': json['tag'],
    };
}

export function CashtagEntityToJSON(value?: CashtagEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'end': value.end,
        'start': value.start,
        'tag': value.tag,
    };
}

