/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of compliance job to list.
 * @export
 */
export const ComplianceJobType = {
    Tweets: 'tweets',
    Users: 'users'
} as const;
export type ComplianceJobType = typeof ComplianceJobType[keyof typeof ComplianceJobType];


export function ComplianceJobTypeFromJSON(json: any): ComplianceJobType {
    return ComplianceJobTypeFromJSONTyped(json, false);
}

export function ComplianceJobTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplianceJobType {
    return json as ComplianceJobType;
}

export function ComplianceJobTypeToJSON(value?: ComplianceJobType | null): any {
    return value as any;
}

