/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of a compliance job.
 * @export
 */
export const ComplianceJobStatus = {
    Created: 'created',
    InProgress: 'in_progress',
    Failed: 'failed',
    Complete: 'complete',
    Expired: 'expired'
} as const;
export type ComplianceJobStatus = typeof ComplianceJobStatus[keyof typeof ComplianceJobStatus];


export function ComplianceJobStatusFromJSON(json: any): ComplianceJobStatus {
    return ComplianceJobStatusFromJSONTyped(json, false);
}

export function ComplianceJobStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplianceJobStatus {
    return json as ComplianceJobStatus;
}

export function ComplianceJobStatusToJSON(value?: ComplianceJobStatus | null): any {
    return value as any;
}

