/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ComplianceJob } from './ComplianceJob';
import {
    ComplianceJobFromJSON,
    ComplianceJobFromJSONTyped,
    ComplianceJobToJSON,
} from './ComplianceJob';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';

/**
 * 
 * @export
 * @interface CreateComplianceJobResponse
 */
export interface CreateComplianceJobResponse {
    /**
     * 
     * @type {ComplianceJob}
     * @memberof CreateComplianceJobResponse
     */
    data?: ComplianceJob;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof CreateComplianceJobResponse
     */
    errors?: Array<Problem>;
}

/**
 * Check if a given object implements the CreateComplianceJobResponse interface.
 */
export function instanceOfCreateComplianceJobResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateComplianceJobResponseFromJSON(json: any): CreateComplianceJobResponse {
    return CreateComplianceJobResponseFromJSONTyped(json, false);
}

export function CreateComplianceJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateComplianceJobResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ComplianceJobFromJSON(json['data']),
        'errors': !exists(json, 'errors') ? undefined : ((json['errors'] as Array<any>).map(ProblemFromJSON)),
    };
}

export function CreateComplianceJobResponseToJSON(value?: CreateComplianceJobResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ComplianceJobToJSON(value.data),
        'errors': value.errors === undefined ? undefined : ((value.errors as Array<any>).map(ProblemToJSON)),
    };
}

