/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * IDs and values of all deleted user-specified stream filtering rules.
 * @export
 * @interface DeleteRulesRequestDelete
 */
export interface DeleteRulesRequestDelete {
    /**
     * IDs of all deleted user-specified stream filtering rules.
     * @type {Array<string>}
     * @memberof DeleteRulesRequestDelete
     */
    ids?: Array<string>;
    /**
     * Values of all deleted user-specified stream filtering rules.
     * @type {Array<string>}
     * @memberof DeleteRulesRequestDelete
     */
    values?: Array<string>;
}

/**
 * Check if a given object implements the DeleteRulesRequestDelete interface.
 */
export function instanceOfDeleteRulesRequestDelete(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeleteRulesRequestDeleteFromJSON(json: any): DeleteRulesRequestDelete {
    return DeleteRulesRequestDeleteFromJSONTyped(json, false);
}

export function DeleteRulesRequestDeleteFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteRulesRequestDelete {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ids': !exists(json, 'ids') ? undefined : json['ids'],
        'values': !exists(json, 'values') ? undefined : json['values'],
    };
}

export function DeleteRulesRequestDeleteToJSON(value?: DeleteRulesRequestDelete | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ids': value.ids,
        'values': value.values,
    };
}

