/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DisallowedResourceProblemAllOf } from './DisallowedResourceProblemAllOf';
import {
    DisallowedResourceProblemAllOfFromJSON,
    DisallowedResourceProblemAllOfFromJSONTyped,
    DisallowedResourceProblemAllOfToJSON,
} from './DisallowedResourceProblemAllOf';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';

/**
 * A problem that indicates that the resource requested violates the precepts of this API.
 * @export
 * @interface DisallowedResourceProblem
 */
export interface DisallowedResourceProblem extends Problem {
    /**
     * 
     * @type {string}
     * @memberof DisallowedResourceProblem
     */
    resourceId: string;
    /**
     * 
     * @type {string}
     * @memberof DisallowedResourceProblem
     */
    resourceType: DisallowedResourceProblemResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof DisallowedResourceProblem
     */
    section: DisallowedResourceProblemSectionEnum;
}


/**
 * @export
 */
export const DisallowedResourceProblemResourceTypeEnum = {
    User: 'user',
    Tweet: 'tweet',
    Media: 'media',
    List: 'list',
    Space: 'space'
} as const;
export type DisallowedResourceProblemResourceTypeEnum = typeof DisallowedResourceProblemResourceTypeEnum[keyof typeof DisallowedResourceProblemResourceTypeEnum];

/**
 * @export
 */
export const DisallowedResourceProblemSectionEnum = {
    Data: 'data',
    Includes: 'includes'
} as const;
export type DisallowedResourceProblemSectionEnum = typeof DisallowedResourceProblemSectionEnum[keyof typeof DisallowedResourceProblemSectionEnum];


/**
 * Check if a given object implements the DisallowedResourceProblem interface.
 */
export function instanceOfDisallowedResourceProblem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "resourceId" in value;
    isInstance = isInstance && "resourceType" in value;
    isInstance = isInstance && "section" in value;

    return isInstance;
}

export function DisallowedResourceProblemFromJSON(json: any): DisallowedResourceProblem {
    return DisallowedResourceProblemFromJSONTyped(json, false);
}

export function DisallowedResourceProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DisallowedResourceProblem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...ProblemFromJSONTyped(json, ignoreDiscriminator),
        'resourceId': json['resource_id'],
        'resourceType': json['resource_type'],
        'section': json['section'],
    };
}

export function DisallowedResourceProblemToJSON(value?: DisallowedResourceProblem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...ProblemToJSON(value),
        'resource_id': value.resourceId,
        'resource_type': value.resourceType,
        'section': value.section,
    };
}

