/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Expansions } from './Expansions';
import {
    ExpansionsFromJSON,
    ExpansionsFromJSONTyped,
    ExpansionsToJSON,
} from './Expansions';
import type { FilteredStreamingTweetResponseMatchingRulesInner } from './FilteredStreamingTweetResponseMatchingRulesInner';
import {
    FilteredStreamingTweetResponseMatchingRulesInnerFromJSON,
    FilteredStreamingTweetResponseMatchingRulesInnerFromJSONTyped,
    FilteredStreamingTweetResponseMatchingRulesInnerToJSON,
} from './FilteredStreamingTweetResponseMatchingRulesInner';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';
import type { Tweet } from './Tweet';
import {
    TweetFromJSON,
    TweetFromJSONTyped,
    TweetToJSON,
} from './Tweet';

/**
 * A Tweet or error that can be returned by the streaming Tweet API. The values returned with a successful streamed Tweet includes the user provided rules that the Tweet matched.
 * @export
 * @interface FilteredStreamingTweetResponse
 */
export interface FilteredStreamingTweetResponse {
    /**
     * 
     * @type {Tweet}
     * @memberof FilteredStreamingTweetResponse
     */
    data?: Tweet;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof FilteredStreamingTweetResponse
     */
    errors?: Array<Problem>;
    /**
     * 
     * @type {Expansions}
     * @memberof FilteredStreamingTweetResponse
     */
    includes?: Expansions;
    /**
     * The list of rules which matched the Tweet
     * @type {Array<FilteredStreamingTweetResponseMatchingRulesInner>}
     * @memberof FilteredStreamingTweetResponse
     */
    matchingRules?: Array<FilteredStreamingTweetResponseMatchingRulesInner>;
}

/**
 * Check if a given object implements the FilteredStreamingTweetResponse interface.
 */
export function instanceOfFilteredStreamingTweetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FilteredStreamingTweetResponseFromJSON(json: any): FilteredStreamingTweetResponse {
    return FilteredStreamingTweetResponseFromJSONTyped(json, false);
}

export function FilteredStreamingTweetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilteredStreamingTweetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : TweetFromJSON(json['data']),
        'errors': !exists(json, 'errors') ? undefined : ((json['errors'] as Array<any>).map(ProblemFromJSON)),
        'includes': !exists(json, 'includes') ? undefined : ExpansionsFromJSON(json['includes']),
        'matchingRules': !exists(json, 'matching_rules') ? undefined : ((json['matching_rules'] as Array<any>).map(FilteredStreamingTweetResponseMatchingRulesInnerFromJSON)),
    };
}

export function FilteredStreamingTweetResponseToJSON(value?: FilteredStreamingTweetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': TweetToJSON(value.data),
        'errors': value.errors === undefined ? undefined : ((value.errors as Array<any>).map(ProblemToJSON)),
        'includes': ExpansionsToJSON(value.includes),
        'matching_rules': value.matchingRules === undefined ? undefined : ((value.matchingRules as Array<any>).map(FilteredStreamingTweetResponseMatchingRulesInnerToJSON)),
    };
}

