/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FilteredStreamingTweetResponseMatchingRulesInner
 */
export interface FilteredStreamingTweetResponseMatchingRulesInner {
    /**
     * Unique identifier of this rule.
     * @type {string}
     * @memberof FilteredStreamingTweetResponseMatchingRulesInner
     */
    id: string;
    /**
     * A tag meant for the labeling of user provided rules.
     * @type {string}
     * @memberof FilteredStreamingTweetResponseMatchingRulesInner
     */
    tag?: string;
}

/**
 * Check if a given object implements the FilteredStreamingTweetResponseMatchingRulesInner interface.
 */
export function instanceOfFilteredStreamingTweetResponseMatchingRulesInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function FilteredStreamingTweetResponseMatchingRulesInnerFromJSON(json: any): FilteredStreamingTweetResponseMatchingRulesInner {
    return FilteredStreamingTweetResponseMatchingRulesInnerFromJSONTyped(json, false);
}

export function FilteredStreamingTweetResponseMatchingRulesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilteredStreamingTweetResponseMatchingRulesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tag': !exists(json, 'tag') ? undefined : json['tag'],
    };
}

export function FilteredStreamingTweetResponseMatchingRulesInnerToJSON(value?: FilteredStreamingTweetResponseMatchingRulesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'tag': value.tag,
    };
}

