/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Expansions } from './Expansions';
import {
    ExpansionsFromJSON,
    ExpansionsFromJSONTyped,
    ExpansionsToJSON,
} from './Expansions';
import type { List } from './List';
import {
    ListFromJSON,
    ListFromJSONTyped,
    ListToJSON,
} from './List';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';

/**
 * 
 * @export
 * @interface Get2ListsIdResponse
 */
export interface Get2ListsIdResponse {
    /**
     * 
     * @type {List}
     * @memberof Get2ListsIdResponse
     */
    data?: List;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof Get2ListsIdResponse
     */
    errors?: Array<Problem>;
    /**
     * 
     * @type {Expansions}
     * @memberof Get2ListsIdResponse
     */
    includes?: Expansions;
}

/**
 * Check if a given object implements the Get2ListsIdResponse interface.
 */
export function instanceOfGet2ListsIdResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Get2ListsIdResponseFromJSON(json: any): Get2ListsIdResponse {
    return Get2ListsIdResponseFromJSONTyped(json, false);
}

export function Get2ListsIdResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Get2ListsIdResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ListFromJSON(json['data']),
        'errors': !exists(json, 'errors') ? undefined : ((json['errors'] as Array<any>).map(ProblemFromJSON)),
        'includes': !exists(json, 'includes') ? undefined : ExpansionsFromJSON(json['includes']),
    };
}

export function Get2ListsIdResponseToJSON(value?: Get2ListsIdResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ListToJSON(value.data),
        'errors': value.errors === undefined ? undefined : ((value.errors as Array<any>).map(ProblemToJSON)),
        'includes': ExpansionsToJSON(value.includes),
    };
}

