/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Get2TweetsIdQuoteTweetsResponseMeta
 */
export interface Get2TweetsIdQuoteTweetsResponseMeta {
    /**
     * The next token.
     * @type {string}
     * @memberof Get2TweetsIdQuoteTweetsResponseMeta
     */
    nextToken?: string;
    /**
     * The number of results returned in this response.
     * @type {number}
     * @memberof Get2TweetsIdQuoteTweetsResponseMeta
     */
    resultCount?: number;
}

/**
 * Check if a given object implements the Get2TweetsIdQuoteTweetsResponseMeta interface.
 */
export function instanceOfGet2TweetsIdQuoteTweetsResponseMeta(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Get2TweetsIdQuoteTweetsResponseMetaFromJSON(json: any): Get2TweetsIdQuoteTweetsResponseMeta {
    return Get2TweetsIdQuoteTweetsResponseMetaFromJSONTyped(json, false);
}

export function Get2TweetsIdQuoteTweetsResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Get2TweetsIdQuoteTweetsResponseMeta {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nextToken': !exists(json, 'next_token') ? undefined : json['next_token'],
        'resultCount': !exists(json, 'result_count') ? undefined : json['result_count'],
    };
}

export function Get2TweetsIdQuoteTweetsResponseMetaToJSON(value?: Get2TweetsIdQuoteTweetsResponseMeta | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'next_token': value.nextToken,
        'result_count': value.resultCount,
    };
}

