/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Get2TweetsSearchAllResponseMeta
 */
export interface Get2TweetsSearchAllResponseMeta {
    /**
     * The newest id in this response.
     * @type {string}
     * @memberof Get2TweetsSearchAllResponseMeta
     */
    newestId?: string;
    /**
     * The next token.
     * @type {string}
     * @memberof Get2TweetsSearchAllResponseMeta
     */
    nextToken?: string;
    /**
     * The oldest id in this response.
     * @type {string}
     * @memberof Get2TweetsSearchAllResponseMeta
     */
    oldestId?: string;
    /**
     * The number of results returned in this response.
     * @type {number}
     * @memberof Get2TweetsSearchAllResponseMeta
     */
    resultCount?: number;
}

/**
 * Check if a given object implements the Get2TweetsSearchAllResponseMeta interface.
 */
export function instanceOfGet2TweetsSearchAllResponseMeta(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Get2TweetsSearchAllResponseMetaFromJSON(json: any): Get2TweetsSearchAllResponseMeta {
    return Get2TweetsSearchAllResponseMetaFromJSONTyped(json, false);
}

export function Get2TweetsSearchAllResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Get2TweetsSearchAllResponseMeta {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'newestId': !exists(json, 'newest_id') ? undefined : json['newest_id'],
        'nextToken': !exists(json, 'next_token') ? undefined : json['next_token'],
        'oldestId': !exists(json, 'oldest_id') ? undefined : json['oldest_id'],
        'resultCount': !exists(json, 'result_count') ? undefined : json['result_count'],
    };
}

export function Get2TweetsSearchAllResponseMetaToJSON(value?: Get2TweetsSearchAllResponseMeta | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'newest_id': value.newestId,
        'next_token': value.nextToken,
        'oldest_id': value.oldestId,
        'result_count': value.resultCount,
    };
}

