/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Expansions } from './Expansions';
import {
    ExpansionsFromJSON,
    ExpansionsFromJSONTyped,
    ExpansionsToJSON,
} from './Expansions';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface Get2UsersMeResponse
 */
export interface Get2UsersMeResponse {
    /**
     * 
     * @type {User}
     * @memberof Get2UsersMeResponse
     */
    data?: User;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof Get2UsersMeResponse
     */
    errors?: Array<Problem>;
    /**
     * 
     * @type {Expansions}
     * @memberof Get2UsersMeResponse
     */
    includes?: Expansions;
}

/**
 * Check if a given object implements the Get2UsersMeResponse interface.
 */
export function instanceOfGet2UsersMeResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Get2UsersMeResponseFromJSON(json: any): Get2UsersMeResponse {
    return Get2UsersMeResponseFromJSONTyped(json, false);
}

export function Get2UsersMeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Get2UsersMeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : UserFromJSON(json['data']),
        'errors': !exists(json, 'errors') ? undefined : ((json['errors'] as Array<any>).map(ProblemFromJSON)),
        'includes': !exists(json, 'includes') ? undefined : ExpansionsFromJSON(json['includes']),
    };
}

export function Get2UsersMeResponseToJSON(value?: Get2UsersMeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': UserToJSON(value.data),
        'errors': value.errors === undefined ? undefined : ((value.errors as Array<any>).map(ProblemToJSON)),
        'includes': ExpansionsToJSON(value.includes),
    };
}

