/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Get2TweetsCountsAllResponseMeta } from './Get2TweetsCountsAllResponseMeta';
import {
    Get2TweetsCountsAllResponseMetaFromJSON,
    Get2TweetsCountsAllResponseMetaFromJSONTyped,
    Get2TweetsCountsAllResponseMetaToJSON,
} from './Get2TweetsCountsAllResponseMeta';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';
import type { SearchCount } from './SearchCount';
import {
    SearchCountFromJSON,
    SearchCountFromJSONTyped,
    SearchCountToJSON,
} from './SearchCount';

/**
 * 
 * @export
 * @interface Get2TweetsCountsRecentResponse
 */
export interface Get2TweetsCountsRecentResponse {
    /**
     * 
     * @type {Array<SearchCount>}
     * @memberof Get2TweetsCountsRecentResponse
     */
    data?: Array<SearchCount>;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof Get2TweetsCountsRecentResponse
     */
    errors?: Array<Problem>;
    /**
     * 
     * @type {Get2TweetsCountsAllResponseMeta}
     * @memberof Get2TweetsCountsRecentResponse
     */
    meta?: Get2TweetsCountsAllResponseMeta;
}

/**
 * Check if a given object implements the Get2TweetsCountsRecentResponse interface.
 */
export function instanceOfGet2TweetsCountsRecentResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Get2TweetsCountsRecentResponseFromJSON(json: any): Get2TweetsCountsRecentResponse {
    return Get2TweetsCountsRecentResponseFromJSONTyped(json, false);
}

export function Get2TweetsCountsRecentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Get2TweetsCountsRecentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(SearchCountFromJSON)),
        'errors': !exists(json, 'errors') ? undefined : ((json['errors'] as Array<any>).map(ProblemFromJSON)),
        'meta': !exists(json, 'meta') ? undefined : Get2TweetsCountsAllResponseMetaFromJSON(json['meta']),
    };
}

export function Get2TweetsCountsRecentResponseToJSON(value?: Get2TweetsCountsRecentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(SearchCountToJSON)),
        'errors': value.errors === undefined ? undefined : ((value.errors as Array<any>).map(ProblemToJSON)),
        'meta': Get2TweetsCountsAllResponseMetaToJSON(value.meta),
    };
}

