/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EntityIndicesInclusiveExclusive } from './EntityIndicesInclusiveExclusive';
import {
    EntityIndicesInclusiveExclusiveFromJSON,
    EntityIndicesInclusiveExclusiveFromJSONTyped,
    EntityIndicesInclusiveExclusiveToJSON,
} from './EntityIndicesInclusiveExclusive';
import type { HashtagFields } from './HashtagFields';
import {
    HashtagFieldsFromJSON,
    HashtagFieldsFromJSONTyped,
    HashtagFieldsToJSON,
} from './HashtagFields';

/**
 * 
 * @export
 * @interface HashtagEntity
 */
export interface HashtagEntity {
    /**
     * Index (zero-based) at which position this entity ends.  The index is exclusive.
     * @type {number}
     * @memberof HashtagEntity
     */
    end: number;
    /**
     * Index (zero-based) at which position this entity starts.  The index is inclusive.
     * @type {number}
     * @memberof HashtagEntity
     */
    start: number;
    /**
     * The text of the Hashtag.
     * @type {string}
     * @memberof HashtagEntity
     */
    tag: string;
}

/**
 * Check if a given object implements the HashtagEntity interface.
 */
export function instanceOfHashtagEntity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "end" in value;
    isInstance = isInstance && "start" in value;
    isInstance = isInstance && "tag" in value;

    return isInstance;
}

export function HashtagEntityFromJSON(json: any): HashtagEntity {
    return HashtagEntityFromJSONTyped(json, false);
}

export function HashtagEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): HashtagEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'end': json['end'],
        'start': json['start'],
        'tag': json['tag'],
    };
}

export function HashtagEntityToJSON(value?: HashtagEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'end': value.end,
        'start': value.start,
        'tag': value.tag,
    };
}

