/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Represent the portion of text recognized as a Hashtag, and its start and end position within the text.
 * @export
 * @interface HashtagFields
 */
export interface HashtagFields {
    /**
     * The text of the Hashtag.
     * @type {string}
     * @memberof HashtagFields
     */
    tag: string;
}

/**
 * Check if a given object implements the HashtagFields interface.
 */
export function instanceOfHashtagFields(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tag" in value;

    return isInstance;
}

export function HashtagFieldsFromJSON(json: any): HashtagFields {
    return HashtagFieldsFromJSONTyped(json, false);
}

export function HashtagFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): HashtagFields {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tag': json['tag'],
    };
}

export function HashtagFieldsToJSON(value?: HashtagFields | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tag': value.tag,
    };
}

