/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InvalidRequestProblemAllOfErrors } from './InvalidRequestProblemAllOfErrors';
import {
    InvalidRequestProblemAllOfErrorsFromJSON,
    InvalidRequestProblemAllOfErrorsFromJSONTyped,
    InvalidRequestProblemAllOfErrorsToJSON,
} from './InvalidRequestProblemAllOfErrors';

/**
 * 
 * @export
 * @interface InvalidRequestProblemAllOf
 */
export interface InvalidRequestProblemAllOf {
    /**
     * 
     * @type {Array<InvalidRequestProblemAllOfErrors>}
     * @memberof InvalidRequestProblemAllOf
     */
    errors?: Array<InvalidRequestProblemAllOfErrors>;
}

/**
 * Check if a given object implements the InvalidRequestProblemAllOf interface.
 */
export function instanceOfInvalidRequestProblemAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InvalidRequestProblemAllOfFromJSON(json: any): InvalidRequestProblemAllOf {
    return InvalidRequestProblemAllOfFromJSONTyped(json, false);
}

export function InvalidRequestProblemAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvalidRequestProblemAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errors': !exists(json, 'errors') ? undefined : ((json['errors'] as Array<any>).map(InvalidRequestProblemAllOfErrorsFromJSON)),
    };
}

export function InvalidRequestProblemAllOfToJSON(value?: InvalidRequestProblemAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errors': value.errors === undefined ? undefined : ((value.errors as Array<any>).map(InvalidRequestProblemAllOfErrorsToJSON)),
    };
}

