/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';

/**
 * The rule you have submitted is invalid.
 * @export
 * @interface InvalidRuleProblem
 */
export interface InvalidRuleProblem extends Problem {
}

/**
 * Check if a given object implements the InvalidRuleProblem interface.
 */
export function instanceOfInvalidRuleProblem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InvalidRuleProblemFromJSON(json: any): InvalidRuleProblem {
    return InvalidRuleProblemFromJSONTyped(json, false);
}

export function InvalidRuleProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvalidRuleProblem {
    return json;
}

export function InvalidRuleProblemToJSON(value?: InvalidRuleProblem | null): any {
    return value;
}

