/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InvalidRequestProblemAllOf } from './InvalidRequestProblemAllOf';
import {
    InvalidRequestProblemAllOfFromJSON,
    InvalidRequestProblemAllOfFromJSONTyped,
    InvalidRequestProblemAllOfToJSON,
} from './InvalidRequestProblemAllOf';
import type { InvalidRequestProblemAllOfErrors } from './InvalidRequestProblemAllOfErrors';
import {
    InvalidRequestProblemAllOfErrorsFromJSON,
    InvalidRequestProblemAllOfErrorsFromJSONTyped,
    InvalidRequestProblemAllOfErrorsToJSON,
} from './InvalidRequestProblemAllOfErrors';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';

/**
 * A problem that indicates this request is invalid.
 * @export
 * @interface InvalidRequestProblem
 */
export interface InvalidRequestProblem extends Problem {
    /**
     * 
     * @type {Array<InvalidRequestProblemAllOfErrors>}
     * @memberof InvalidRequestProblem
     */
    errors?: Array<InvalidRequestProblemAllOfErrors>;
}

/**
 * Check if a given object implements the InvalidRequestProblem interface.
 */
export function instanceOfInvalidRequestProblem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InvalidRequestProblemFromJSON(json: any): InvalidRequestProblem {
    return InvalidRequestProblemFromJSONTyped(json, false);
}

export function InvalidRequestProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvalidRequestProblem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...ProblemFromJSONTyped(json, ignoreDiscriminator),
        'errors': !exists(json, 'errors') ? undefined : ((json['errors'] as Array<any>).map(InvalidRequestProblemAllOfErrorsFromJSON)),
    };
}

export function InvalidRequestProblemToJSON(value?: InvalidRequestProblem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...ProblemToJSON(value),
        'errors': value.errors === undefined ? undefined : ((value.errors as Array<any>).map(InvalidRequestProblemAllOfErrorsToJSON)),
    };
}

