/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ListCreateResponseData } from './ListCreateResponseData';
import {
    ListCreateResponseDataFromJSON,
    ListCreateResponseDataFromJSONTyped,
    ListCreateResponseDataToJSON,
} from './ListCreateResponseData';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';

/**
 * 
 * @export
 * @interface ListCreateResponse
 */
export interface ListCreateResponse {
    /**
     * 
     * @type {ListCreateResponseData}
     * @memberof ListCreateResponse
     */
    data?: ListCreateResponseData;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof ListCreateResponse
     */
    errors?: Array<Problem>;
}

/**
 * Check if a given object implements the ListCreateResponse interface.
 */
export function instanceOfListCreateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListCreateResponseFromJSON(json: any): ListCreateResponse {
    return ListCreateResponseFromJSONTyped(json, false);
}

export function ListCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCreateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ListCreateResponseDataFromJSON(json['data']),
        'errors': !exists(json, 'errors') ? undefined : ((json['errors'] as Array<any>).map(ProblemFromJSON)),
    };
}

export function ListCreateResponseToJSON(value?: ListCreateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ListCreateResponseDataToJSON(value.data),
        'errors': value.errors === undefined ? undefined : ((value.errors as Array<any>).map(ProblemToJSON)),
    };
}

