/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ListDeleteResponseData } from './ListDeleteResponseData';
import {
    ListDeleteResponseDataFromJSON,
    ListDeleteResponseDataFromJSONTyped,
    ListDeleteResponseDataToJSON,
} from './ListDeleteResponseData';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';

/**
 * 
 * @export
 * @interface ListDeleteResponse
 */
export interface ListDeleteResponse {
    /**
     * 
     * @type {ListDeleteResponseData}
     * @memberof ListDeleteResponse
     */
    data?: ListDeleteResponseData;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof ListDeleteResponse
     */
    errors?: Array<Problem>;
}

/**
 * Check if a given object implements the ListDeleteResponse interface.
 */
export function instanceOfListDeleteResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListDeleteResponseFromJSON(json: any): ListDeleteResponse {
    return ListDeleteResponseFromJSONTyped(json, false);
}

export function ListDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDeleteResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ListDeleteResponseDataFromJSON(json['data']),
        'errors': !exists(json, 'errors') ? undefined : ((json['errors'] as Array<any>).map(ProblemFromJSON)),
    };
}

export function ListDeleteResponseToJSON(value?: ListDeleteResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ListDeleteResponseDataToJSON(value.data),
        'errors': value.errors === undefined ? undefined : ((value.errors as Array<any>).map(ProblemToJSON)),
    };
}

