/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListCreateRequest
 */
export interface ListCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof ListCreateRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ListCreateRequest
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListCreateRequest
     */
    _private?: boolean;
}

/**
 * Check if a given object implements the ListCreateRequest interface.
 */
export function instanceOfListCreateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ListCreateRequestFromJSON(json: any): ListCreateRequest {
    return ListCreateRequestFromJSONTyped(json, false);
}

export function ListCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': json['name'],
        '_private': !exists(json, 'private') ? undefined : json['private'],
    };
}

export function ListCreateRequestToJSON(value?: ListCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'name': value.name,
        'private': value._private,
    };
}

