/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListPinnedRequest
 */
export interface ListPinnedRequest {
    /**
     * The unique identifier of this List.
     * @type {string}
     * @memberof ListPinnedRequest
     */
    listId: string;
}

/**
 * Check if a given object implements the ListPinnedRequest interface.
 */
export function instanceOfListPinnedRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "listId" in value;

    return isInstance;
}

export function ListPinnedRequestFromJSON(json: any): ListPinnedRequest {
    return ListPinnedRequestFromJSONTyped(json, false);
}

export function ListPinnedRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPinnedRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'listId': json['list_id'],
    };
}

export function ListPinnedRequestToJSON(value?: ListPinnedRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'list_id': value.listId,
    };
}

