/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListUpdateRequest
 */
export interface ListUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof ListUpdateRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ListUpdateRequest
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListUpdateRequest
     */
    _private?: boolean;
}

/**
 * Check if a given object implements the ListUpdateRequest interface.
 */
export function instanceOfListUpdateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListUpdateRequestFromJSON(json: any): ListUpdateRequest {
    return ListUpdateRequestFromJSONTyped(json, false);
}

export function ListUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListUpdateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        '_private': !exists(json, 'private') ? undefined : json['private'],
    };
}

export function ListUpdateRequestToJSON(value?: ListUpdateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'name': value.name,
        'private': value._private,
    };
}

