/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListPinnedResponseData
 */
export interface ListPinnedResponseData {
    /**
     * 
     * @type {boolean}
     * @memberof ListPinnedResponseData
     */
    pinned?: boolean;
}

/**
 * Check if a given object implements the ListPinnedResponseData interface.
 */
export function instanceOfListPinnedResponseData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListPinnedResponseDataFromJSON(json: any): ListPinnedResponseData {
    return ListPinnedResponseDataFromJSONTyped(json, false);
}

export function ListPinnedResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPinnedResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pinned': !exists(json, 'pinned') ? undefined : json['pinned'],
    };
}

export function ListPinnedResponseDataToJSON(value?: ListPinnedResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pinned': value.pinned,
    };
}

