/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ListPinnedResponseData } from './ListPinnedResponseData';
import {
    ListPinnedResponseDataFromJSON,
    ListPinnedResponseDataFromJSONTyped,
    ListPinnedResponseDataToJSON,
} from './ListPinnedResponseData';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';

/**
 * 
 * @export
 * @interface ListUnpinResponse
 */
export interface ListUnpinResponse {
    /**
     * 
     * @type {ListPinnedResponseData}
     * @memberof ListUnpinResponse
     */
    data?: ListPinnedResponseData;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof ListUnpinResponse
     */
    errors?: Array<Problem>;
}

/**
 * Check if a given object implements the ListUnpinResponse interface.
 */
export function instanceOfListUnpinResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListUnpinResponseFromJSON(json: any): ListUnpinResponse {
    return ListUnpinResponseFromJSONTyped(json, false);
}

export function ListUnpinResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListUnpinResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ListPinnedResponseDataFromJSON(json['data']),
        'errors': !exists(json, 'errors') ? undefined : ((json['errors'] as Array<any>).map(ProblemFromJSON)),
    };
}

export function ListUnpinResponseToJSON(value?: ListUnpinResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ListPinnedResponseDataToJSON(value.data),
        'errors': value.errors === undefined ? undefined : ((value.errors as Array<any>).map(ProblemToJSON)),
    };
}

