/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Represent the portion of text recognized as a User mention, and its start and end position within the text.
 * @export
 * @interface MentionFields
 */
export interface MentionFields {
    /**
     * Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
     * @type {string}
     * @memberof MentionFields
     */
    id?: string;
    /**
     * The Twitter handle (screen name) of this user.
     * @type {string}
     * @memberof MentionFields
     */
    username: string;
}

/**
 * Check if a given object implements the MentionFields interface.
 */
export function instanceOfMentionFields(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function MentionFieldsFromJSON(json: any): MentionFields {
    return MentionFieldsFromJSONTyped(json, false);
}

export function MentionFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MentionFields {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'username': json['username'],
    };
}

export function MentionFieldsToJSON(value?: MentionFields | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'username': value.username,
    };
}

