/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MuteUserRequest
 */
export interface MuteUserRequest {
    /**
     * Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
     * @type {string}
     * @memberof MuteUserRequest
     */
    targetUserId: string;
}

/**
 * Check if a given object implements the MuteUserRequest interface.
 */
export function instanceOfMuteUserRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "targetUserId" in value;

    return isInstance;
}

export function MuteUserRequestFromJSON(json: any): MuteUserRequest {
    return MuteUserRequestFromJSONTyped(json, false);
}

export function MuteUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MuteUserRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'targetUserId': json['target_user_id'],
    };
}

export function MuteUserRequestToJSON(value?: MuteUserRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'target_user_id': value.targetUserId,
    };
}

