/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';

/**
 * A problem that indicates the user's rule set is not compliant.
 * @export
 * @interface NonCompliantRulesProblem
 */
export interface NonCompliantRulesProblem extends Problem {
}

/**
 * Check if a given object implements the NonCompliantRulesProblem interface.
 */
export function instanceOfNonCompliantRulesProblem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NonCompliantRulesProblemFromJSON(json: any): NonCompliantRulesProblem {
    return NonCompliantRulesProblemFromJSONTyped(json, false);
}

export function NonCompliantRulesProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): NonCompliantRulesProblem {
    return json;
}

export function NonCompliantRulesProblemToJSON(value?: NonCompliantRulesProblem | null): any {
    return value;
}

