/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PhotoAllOf
 */
export interface PhotoAllOf {
    /**
     * 
     * @type {string}
     * @memberof PhotoAllOf
     */
    altText?: string;
    /**
     * 
     * @type {string}
     * @memberof PhotoAllOf
     */
    url?: string;
}

/**
 * Check if a given object implements the PhotoAllOf interface.
 */
export function instanceOfPhotoAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PhotoAllOfFromJSON(json: any): PhotoAllOf {
    return PhotoAllOfFromJSONTyped(json, false);
}

export function PhotoAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhotoAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'altText': !exists(json, 'alt_text') ? undefined : json['alt_text'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function PhotoAllOfToJSON(value?: PhotoAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alt_text': value.altText,
        'url': value.url,
    };
}

