/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Media } from './Media';
import {
    MediaFromJSON,
    MediaFromJSONTyped,
    MediaToJSON,
} from './Media';
import type { PhotoAllOf } from './PhotoAllOf';
import {
    PhotoAllOfFromJSON,
    PhotoAllOfFromJSONTyped,
    PhotoAllOfToJSON,
} from './PhotoAllOf';

/**
 * 
 * @export
 * @interface Photo
 */
export interface Photo extends Media {
    /**
     * 
     * @type {string}
     * @memberof Photo
     */
    altText?: string;
    /**
     * 
     * @type {string}
     * @memberof Photo
     */
    url?: string;
}

/**
 * Check if a given object implements the Photo interface.
 */
export function instanceOfPhoto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PhotoFromJSON(json: any): Photo {
    return PhotoFromJSONTyped(json, false);
}

export function PhotoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Photo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...MediaFromJSONTyped(json, ignoreDiscriminator),
        'altText': !exists(json, 'alt_text') ? undefined : json['alt_text'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function PhotoToJSON(value?: Photo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...MediaToJSON(value),
        'alt_text': value.altText,
        'url': value.url,
    };
}

