/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ModelError,
    instanceOfModelError,
    ModelErrorFromJSON,
    ModelErrorFromJSONTyped,
    ModelErrorToJSON,
} from './ModelError';
import {
    Problem,
    instanceOfProblem,
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';

/**
 * @type ProblemOrError
 * Represents the response in case of throwing an exception. Mainly for the openapi-generator
 * @export
 */
export type ProblemOrError = ModelError | Problem;

export function ProblemOrErrorFromJSON(json: any): ProblemOrError {
    return ProblemOrErrorFromJSONTyped(json, false);
}

export function ProblemOrErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProblemOrError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ModelErrorFromJSONTyped(json, true), ...ProblemFromJSONTyped(json, true) };
}

export function ProblemOrErrorToJSON(value?: ProblemOrError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfModelError(value)) {
        return ModelErrorToJSON(value as ModelError);
    }
    if (instanceOfProblem(value)) {
        return ProblemToJSON(value as Problem);
    }

    return {};
}

