/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Shows who can reply a Tweet. Fields returned are everyone, mentioned_users, and following.
 * @export
 */
export const ReplySettings = {
    Everyone: 'everyone',
    MentionedUsers: 'mentionedUsers',
    Following: 'following',
    Other: 'other'
} as const;
export type ReplySettings = typeof ReplySettings[keyof typeof ReplySettings];


export function ReplySettingsFromJSON(json: any): ReplySettings {
    return ReplySettingsFromJSONTyped(json, false);
}

export function ReplySettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplySettings {
    return json as ReplySettings;
}

export function ReplySettingsToJSON(value?: ReplySettings | null): any {
    return value as any;
}

