/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReportUsersResponseData } from './ReportUsersResponseData';
import {
    ReportUsersResponseDataFromJSON,
    ReportUsersResponseDataFromJSONTyped,
    ReportUsersResponseDataToJSON,
} from './ReportUsersResponseData';

/**
 * 
 * @export
 * @interface ReportUsersResponse
 */
export interface ReportUsersResponse {
    /**
     * 
     * @type {ReportUsersResponseData}
     * @memberof ReportUsersResponse
     */
    data?: ReportUsersResponseData;
}

/**
 * Check if a given object implements the ReportUsersResponse interface.
 */
export function instanceOfReportUsersResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReportUsersResponseFromJSON(json: any): ReportUsersResponse {
    return ReportUsersResponseFromJSONTyped(json, false);
}

export function ReportUsersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportUsersResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ReportUsersResponseDataFromJSON(json['data']),
    };
}

export function ReportUsersResponseToJSON(value?: ReportUsersResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ReportUsersResponseDataToJSON(value.data),
    };
}

