/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';
import type { ResourceUnauthorizedProblemAllOf } from './ResourceUnauthorizedProblemAllOf';
import {
    ResourceUnauthorizedProblemAllOfFromJSON,
    ResourceUnauthorizedProblemAllOfFromJSONTyped,
    ResourceUnauthorizedProblemAllOfToJSON,
} from './ResourceUnauthorizedProblemAllOf';

/**
 * A problem that indicates you are not allowed to see a particular Tweet, User, etc.
 * @export
 * @interface ResourceUnauthorizedProblem
 */
export interface ResourceUnauthorizedProblem extends Problem {
    /**
     * 
     * @type {string}
     * @memberof ResourceUnauthorizedProblem
     */
    parameter: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceUnauthorizedProblem
     */
    resourceId: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceUnauthorizedProblem
     */
    resourceType: ResourceUnauthorizedProblemResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResourceUnauthorizedProblem
     */
    section: ResourceUnauthorizedProblemSectionEnum;
    /**
     * 
     * @type {string}
     * @memberof ResourceUnauthorizedProblem
     */
    value: string;
}


/**
 * @export
 */
export const ResourceUnauthorizedProblemResourceTypeEnum = {
    User: 'user',
    Tweet: 'tweet',
    Media: 'media',
    List: 'list',
    Space: 'space'
} as const;
export type ResourceUnauthorizedProblemResourceTypeEnum = typeof ResourceUnauthorizedProblemResourceTypeEnum[keyof typeof ResourceUnauthorizedProblemResourceTypeEnum];

/**
 * @export
 */
export const ResourceUnauthorizedProblemSectionEnum = {
    Data: 'data',
    Includes: 'includes'
} as const;
export type ResourceUnauthorizedProblemSectionEnum = typeof ResourceUnauthorizedProblemSectionEnum[keyof typeof ResourceUnauthorizedProblemSectionEnum];


/**
 * Check if a given object implements the ResourceUnauthorizedProblem interface.
 */
export function instanceOfResourceUnauthorizedProblem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "parameter" in value;
    isInstance = isInstance && "resourceId" in value;
    isInstance = isInstance && "resourceType" in value;
    isInstance = isInstance && "section" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function ResourceUnauthorizedProblemFromJSON(json: any): ResourceUnauthorizedProblem {
    return ResourceUnauthorizedProblemFromJSONTyped(json, false);
}

export function ResourceUnauthorizedProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceUnauthorizedProblem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...ProblemFromJSONTyped(json, ignoreDiscriminator),
        'parameter': json['parameter'],
        'resourceId': json['resource_id'],
        'resourceType': json['resource_type'],
        'section': json['section'],
        'value': json['value'],
    };
}

export function ResourceUnauthorizedProblemToJSON(value?: ResourceUnauthorizedProblem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...ProblemToJSON(value),
        'parameter': value.parameter,
        'resource_id': value.resourceId,
        'resource_type': value.resourceType,
        'section': value.section,
        'value': value.value,
    };
}

