/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceNotFoundProblemAllOf
 */
export interface ResourceNotFoundProblemAllOf {
    /**
     * 
     * @type {string}
     * @memberof ResourceNotFoundProblemAllOf
     */
    parameter: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceNotFoundProblemAllOf
     */
    resourceId: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceNotFoundProblemAllOf
     */
    resourceType: ResourceNotFoundProblemAllOfResourceTypeEnum;
    /**
     * Value will match the schema of the field.
     * @type {string}
     * @memberof ResourceNotFoundProblemAllOf
     */
    value: string;
}


/**
 * @export
 */
export const ResourceNotFoundProblemAllOfResourceTypeEnum = {
    User: 'user',
    Tweet: 'tweet',
    Media: 'media',
    List: 'list',
    Space: 'space'
} as const;
export type ResourceNotFoundProblemAllOfResourceTypeEnum = typeof ResourceNotFoundProblemAllOfResourceTypeEnum[keyof typeof ResourceNotFoundProblemAllOfResourceTypeEnum];


/**
 * Check if a given object implements the ResourceNotFoundProblemAllOf interface.
 */
export function instanceOfResourceNotFoundProblemAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "parameter" in value;
    isInstance = isInstance && "resourceId" in value;
    isInstance = isInstance && "resourceType" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function ResourceNotFoundProblemAllOfFromJSON(json: any): ResourceNotFoundProblemAllOf {
    return ResourceNotFoundProblemAllOfFromJSONTyped(json, false);
}

export function ResourceNotFoundProblemAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceNotFoundProblemAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parameter': json['parameter'],
        'resourceId': json['resource_id'],
        'resourceType': json['resource_type'],
        'value': json['value'],
    };
}

export function ResourceNotFoundProblemAllOfToJSON(value?: ResourceNotFoundProblemAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parameter': value.parameter,
        'resource_id': value.resourceId,
        'resource_type': value.resourceType,
        'value': value.value,
    };
}

