/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';

/**
 * You have exceeded the maximum number of rules.
 * @export
 * @interface RulesCapProblem
 */
export interface RulesCapProblem extends Problem {
}

/**
 * Check if a given object implements the RulesCapProblem interface.
 */
export function instanceOfRulesCapProblem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RulesCapProblemFromJSON(json: any): RulesCapProblem {
    return RulesCapProblemFromJSONTyped(json, false);
}

export function RulesCapProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): RulesCapProblem {
    return json;
}

export function RulesCapProblemToJSON(value?: RulesCapProblem | null): any {
    return value;
}

