/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A user-provided stream filtering rule.
 * @export
 * @interface RuleNoId
 */
export interface RuleNoId {
    /**
     * A tag meant for the labeling of user provided rules.
     * @type {string}
     * @memberof RuleNoId
     */
    tag?: string;
    /**
     * The filterlang value of the rule.
     * @type {string}
     * @memberof RuleNoId
     */
    value: string;
}

/**
 * Check if a given object implements the RuleNoId interface.
 */
export function instanceOfRuleNoId(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function RuleNoIdFromJSON(json: any): RuleNoId {
    return RuleNoIdFromJSONTyped(json, false);
}

export function RuleNoIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuleNoId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tag': !exists(json, 'tag') ? undefined : json['tag'],
        'value': json['value'],
    };
}

export function RuleNoIdToJSON(value?: RuleNoId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tag': value.tag,
        'value': value.value,
    };
}

