/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    RulesRequestSummaryOneOf,
    instanceOfRulesRequestSummaryOneOf,
    RulesRequestSummaryOneOfFromJSON,
    RulesRequestSummaryOneOfFromJSONTyped,
    RulesRequestSummaryOneOfToJSON,
} from './RulesRequestSummaryOneOf';
import {
    RulesRequestSummaryOneOf1,
    instanceOfRulesRequestSummaryOneOf1,
    RulesRequestSummaryOneOf1FromJSON,
    RulesRequestSummaryOneOf1FromJSONTyped,
    RulesRequestSummaryOneOf1ToJSON,
} from './RulesRequestSummaryOneOf1';

/**
 * @type RulesRequestSummary
 * 
 * @export
 */
export type RulesRequestSummary = RulesRequestSummaryOneOf | RulesRequestSummaryOneOf1;

export function RulesRequestSummaryFromJSON(json: any): RulesRequestSummary {
    return RulesRequestSummaryFromJSONTyped(json, false);
}

export function RulesRequestSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RulesRequestSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...RulesRequestSummaryOneOfFromJSONTyped(json, true), ...RulesRequestSummaryOneOf1FromJSONTyped(json, true) };
}

export function RulesRequestSummaryToJSON(value?: RulesRequestSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfRulesRequestSummaryOneOf(value)) {
        return RulesRequestSummaryOneOfToJSON(value as RulesRequestSummaryOneOf);
    }
    if (instanceOfRulesRequestSummaryOneOf1(value)) {
        return RulesRequestSummaryOneOf1ToJSON(value as RulesRequestSummaryOneOf1);
    }

    return {};
}

