/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RulesRequestSummary } from './RulesRequestSummary';
import {
    RulesRequestSummaryFromJSON,
    RulesRequestSummaryFromJSONTyped,
    RulesRequestSummaryToJSON,
} from './RulesRequestSummary';

/**
 * 
 * @export
 * @interface RulesResponseMetadata
 */
export interface RulesResponseMetadata {
    /**
     * The next token.
     * @type {string}
     * @memberof RulesResponseMetadata
     */
    nextToken?: string;
    /**
     * Number of Rules in result set.
     * @type {number}
     * @memberof RulesResponseMetadata
     */
    resultCount?: number;
    /**
     * 
     * @type {string}
     * @memberof RulesResponseMetadata
     */
    sent: string;
    /**
     * 
     * @type {RulesRequestSummary}
     * @memberof RulesResponseMetadata
     */
    summary?: RulesRequestSummary;
}

/**
 * Check if a given object implements the RulesResponseMetadata interface.
 */
export function instanceOfRulesResponseMetadata(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sent" in value;

    return isInstance;
}

export function RulesResponseMetadataFromJSON(json: any): RulesResponseMetadata {
    return RulesResponseMetadataFromJSONTyped(json, false);
}

export function RulesResponseMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RulesResponseMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nextToken': !exists(json, 'next_token') ? undefined : json['next_token'],
        'resultCount': !exists(json, 'result_count') ? undefined : json['result_count'],
        'sent': json['sent'],
        'summary': !exists(json, 'summary') ? undefined : RulesRequestSummaryFromJSON(json['summary']),
    };
}

export function RulesResponseMetadataToJSON(value?: RulesResponseMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'next_token': value.nextToken,
        'result_count': value.resultCount,
        'sent': value.sent,
        'summary': RulesRequestSummaryToJSON(value.summary),
    };
}

