/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A summary of the results of the addition of user-specified stream filtering rules.
 * @export
 * @interface RulesRequestSummaryOneOf
 */
export interface RulesRequestSummaryOneOf {
    /**
     * Number of user-specified stream filtering rules that were created.
     * @type {number}
     * @memberof RulesRequestSummaryOneOf
     */
    created: number;
    /**
     * Number of invalid user-specified stream filtering rules.
     * @type {number}
     * @memberof RulesRequestSummaryOneOf
     */
    invalid: number;
    /**
     * Number of user-specified stream filtering rules that were not created.
     * @type {number}
     * @memberof RulesRequestSummaryOneOf
     */
    notCreated: number;
    /**
     * Number of valid user-specified stream filtering rules.
     * @type {number}
     * @memberof RulesRequestSummaryOneOf
     */
    valid: number;
}

/**
 * Check if a given object implements the RulesRequestSummaryOneOf interface.
 */
export function instanceOfRulesRequestSummaryOneOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "created" in value;
    isInstance = isInstance && "invalid" in value;
    isInstance = isInstance && "notCreated" in value;
    isInstance = isInstance && "valid" in value;

    return isInstance;
}

export function RulesRequestSummaryOneOfFromJSON(json: any): RulesRequestSummaryOneOf {
    return RulesRequestSummaryOneOfFromJSONTyped(json, false);
}

export function RulesRequestSummaryOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): RulesRequestSummaryOneOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'created': json['created'],
        'invalid': json['invalid'],
        'notCreated': json['not_created'],
        'valid': json['valid'],
    };
}

export function RulesRequestSummaryOneOfToJSON(value?: RulesRequestSummaryOneOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created': value.created,
        'invalid': value.invalid,
        'not_created': value.notCreated,
        'valid': value.valid,
    };
}

