/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Rule } from './Rule';
import {
    RuleFromJSON,
    RuleFromJSONTyped,
    RuleToJSON,
} from './Rule';
import type { RulesResponseMetadata } from './RulesResponseMetadata';
import {
    RulesResponseMetadataFromJSON,
    RulesResponseMetadataFromJSONTyped,
    RulesResponseMetadataToJSON,
} from './RulesResponseMetadata';

/**
 * 
 * @export
 * @interface RulesLookupResponse
 */
export interface RulesLookupResponse {
    /**
     * 
     * @type {Array<Rule>}
     * @memberof RulesLookupResponse
     */
    data?: Array<Rule>;
    /**
     * 
     * @type {RulesResponseMetadata}
     * @memberof RulesLookupResponse
     */
    meta: RulesResponseMetadata;
}

/**
 * Check if a given object implements the RulesLookupResponse interface.
 */
export function instanceOfRulesLookupResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "meta" in value;

    return isInstance;
}

export function RulesLookupResponseFromJSON(json: any): RulesLookupResponse {
    return RulesLookupResponseFromJSONTyped(json, false);
}

export function RulesLookupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RulesLookupResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(RuleFromJSON)),
        'meta': RulesResponseMetadataFromJSON(json['meta']),
    };
}

export function RulesLookupResponseToJSON(value?: RulesLookupResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(RuleToJSON)),
        'meta': RulesResponseMetadataToJSON(value.meta),
    };
}

