/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The Twitter Topic object.
 * @export
 * @interface SpaceTopicsInner
 */
export interface SpaceTopicsInner {
    /**
     * The description of the given topic.
     * @type {string}
     * @memberof SpaceTopicsInner
     */
    description?: string;
    /**
     * An ID suitable for use in the REST API.
     * @type {string}
     * @memberof SpaceTopicsInner
     */
    id: string;
    /**
     * The name of the given topic.
     * @type {string}
     * @memberof SpaceTopicsInner
     */
    name: string;
}

/**
 * Check if a given object implements the SpaceTopicsInner interface.
 */
export function instanceOfSpaceTopicsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function SpaceTopicsInnerFromJSON(json: any): SpaceTopicsInner {
    return SpaceTopicsInnerFromJSONTyped(json, false);
}

export function SpaceTopicsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpaceTopicsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'id': json['id'],
        'name': json['name'],
    };
}

export function SpaceTopicsInnerToJSON(value?: SpaceTopicsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'id': value.id,
        'name': value.name,
    };
}

