/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Point } from './Point';
import {
    PointFromJSON,
    PointFromJSONTyped,
    PointToJSON,
} from './Point';

/**
 * The location tagged on the Tweet, if the user provided one.
 * @export
 * @interface TweetGeo
 */
export interface TweetGeo {
    /**
     * 
     * @type {Point}
     * @memberof TweetGeo
     */
    coordinates?: Point;
    /**
     * The identifier for this place.
     * @type {string}
     * @memberof TweetGeo
     */
    placeId?: string;
}

/**
 * Check if a given object implements the TweetGeo interface.
 */
export function instanceOfTweetGeo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TweetGeoFromJSON(json: any): TweetGeo {
    return TweetGeoFromJSONTyped(json, false);
}

export function TweetGeoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetGeo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'coordinates': !exists(json, 'coordinates') ? undefined : PointFromJSON(json['coordinates']),
        'placeId': !exists(json, 'place_id') ? undefined : json['place_id'],
    };
}

export function TweetGeoToJSON(value?: TweetGeo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'coordinates': PointToJSON(value.coordinates),
        'place_id': value.placeId,
    };
}

