/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TweetHideResponseData } from './TweetHideResponseData';
import {
    TweetHideResponseDataFromJSON,
    TweetHideResponseDataFromJSONTyped,
    TweetHideResponseDataToJSON,
} from './TweetHideResponseData';

/**
 * 
 * @export
 * @interface TweetHideResponse
 */
export interface TweetHideResponse {
    /**
     * 
     * @type {TweetHideResponseData}
     * @memberof TweetHideResponse
     */
    data?: TweetHideResponseData;
}

/**
 * Check if a given object implements the TweetHideResponse interface.
 */
export function instanceOfTweetHideResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TweetHideResponseFromJSON(json: any): TweetHideResponse {
    return TweetHideResponseFromJSONTyped(json, false);
}

export function TweetHideResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetHideResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : TweetHideResponseDataFromJSON(json['data']),
    };
}

export function TweetHideResponseToJSON(value?: TweetHideResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': TweetHideResponseDataToJSON(value.data),
    };
}

