/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TweetCreateResponseData
 */
export interface TweetCreateResponseData {
    /**
     * Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
     * @type {string}
     * @memberof TweetCreateResponseData
     */
    id: string;
    /**
     * The content of the Tweet.
     * @type {string}
     * @memberof TweetCreateResponseData
     */
    text: string;
}

/**
 * Check if a given object implements the TweetCreateResponseData interface.
 */
export function instanceOfTweetCreateResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "text" in value;

    return isInstance;
}

export function TweetCreateResponseDataFromJSON(json: any): TweetCreateResponseData {
    return TweetCreateResponseDataFromJSONTyped(json, false);
}

export function TweetCreateResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetCreateResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'text': json['text'],
    };
}

export function TweetCreateResponseDataToJSON(value?: TweetCreateResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'text': value.text,
    };
}

