/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';
import type { TweetCreateResponseData } from './TweetCreateResponseData';
import {
    TweetCreateResponseDataFromJSON,
    TweetCreateResponseDataFromJSONTyped,
    TweetCreateResponseDataToJSON,
} from './TweetCreateResponseData';

/**
 * 
 * @export
 * @interface TweetCreateResponse
 */
export interface TweetCreateResponse {
    /**
     * 
     * @type {TweetCreateResponseData}
     * @memberof TweetCreateResponse
     */
    data?: TweetCreateResponseData;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof TweetCreateResponse
     */
    errors?: Array<Problem>;
}

/**
 * Check if a given object implements the TweetCreateResponse interface.
 */
export function instanceOfTweetCreateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TweetCreateResponseFromJSON(json: any): TweetCreateResponse {
    return TweetCreateResponseFromJSONTyped(json, false);
}

export function TweetCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetCreateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : TweetCreateResponseDataFromJSON(json['data']),
        'errors': !exists(json, 'errors') ? undefined : ((json['errors'] as Array<any>).map(ProblemFromJSON)),
    };
}

export function TweetCreateResponseToJSON(value?: TweetCreateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': TweetCreateResponseDataToJSON(value.data),
        'errors': value.errors === undefined ? undefined : ((value.errors as Array<any>).map(ProblemToJSON)),
    };
}

