/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Organic nonpublic engagement metrics for the Tweet at the time of the request.
 * @export
 * @interface TweetOrganicMetrics
 */
export interface TweetOrganicMetrics {
    /**
     * Number of times this Tweet has been viewed.
     * @type {number}
     * @memberof TweetOrganicMetrics
     */
    impressionCount: number;
    /**
     * Number of times this Tweet has been liked.
     * @type {number}
     * @memberof TweetOrganicMetrics
     */
    likeCount: number;
    /**
     * Number of times this Tweet has been replied to.
     * @type {number}
     * @memberof TweetOrganicMetrics
     */
    replyCount: number;
    /**
     * Number of times this Tweet has been Retweeted.
     * @type {number}
     * @memberof TweetOrganicMetrics
     */
    retweetCount: number;
}

/**
 * Check if a given object implements the TweetOrganicMetrics interface.
 */
export function instanceOfTweetOrganicMetrics(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "impressionCount" in value;
    isInstance = isInstance && "likeCount" in value;
    isInstance = isInstance && "replyCount" in value;
    isInstance = isInstance && "retweetCount" in value;

    return isInstance;
}

export function TweetOrganicMetricsFromJSON(json: any): TweetOrganicMetrics {
    return TweetOrganicMetricsFromJSONTyped(json, false);
}

export function TweetOrganicMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetOrganicMetrics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'impressionCount': json['impression_count'],
        'likeCount': json['like_count'],
        'replyCount': json['reply_count'],
        'retweetCount': json['retweet_count'],
    };
}

export function TweetOrganicMetricsToJSON(value?: TweetOrganicMetrics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'impression_count': value.impressionCount,
        'like_count': value.likeCount,
        'reply_count': value.replyCount,
        'retweet_count': value.retweetCount,
    };
}

