/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TweetDeleteResponseData
 */
export interface TweetDeleteResponseData {
    /**
     * 
     * @type {boolean}
     * @memberof TweetDeleteResponseData
     */
    deleted: boolean;
}

/**
 * Check if a given object implements the TweetDeleteResponseData interface.
 */
export function instanceOfTweetDeleteResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "deleted" in value;

    return isInstance;
}

export function TweetDeleteResponseDataFromJSON(json: any): TweetDeleteResponseData {
    return TweetDeleteResponseDataFromJSONTyped(json, false);
}

export function TweetDeleteResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetDeleteResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deleted': json['deleted'],
    };
}

export function TweetDeleteResponseDataToJSON(value?: TweetDeleteResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deleted': value.deleted,
    };
}

