/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    TweetComplianceStreamResponseOneOf,
    instanceOfTweetComplianceStreamResponseOneOf,
    TweetComplianceStreamResponseOneOfFromJSON,
    TweetComplianceStreamResponseOneOfFromJSONTyped,
    TweetComplianceStreamResponseOneOfToJSON,
} from './TweetComplianceStreamResponseOneOf';
import {
    TweetComplianceStreamResponseOneOf1,
    instanceOfTweetComplianceStreamResponseOneOf1,
    TweetComplianceStreamResponseOneOf1FromJSON,
    TweetComplianceStreamResponseOneOf1FromJSONTyped,
    TweetComplianceStreamResponseOneOf1ToJSON,
} from './TweetComplianceStreamResponseOneOf1';

/**
 * @type TweetComplianceStreamResponse
 * Tweet compliance stream events.
 * @export
 */
export type TweetComplianceStreamResponse = TweetComplianceStreamResponseOneOf | TweetComplianceStreamResponseOneOf1;

export function TweetComplianceStreamResponseFromJSON(json: any): TweetComplianceStreamResponse {
    return TweetComplianceStreamResponseFromJSONTyped(json, false);
}

export function TweetComplianceStreamResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetComplianceStreamResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...TweetComplianceStreamResponseOneOfFromJSONTyped(json, true), ...TweetComplianceStreamResponseOneOf1FromJSONTyped(json, true) };
}

export function TweetComplianceStreamResponseToJSON(value?: TweetComplianceStreamResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfTweetComplianceStreamResponseOneOf(value)) {
        return TweetComplianceStreamResponseOneOfToJSON(value as TweetComplianceStreamResponseOneOf);
    }
    if (instanceOfTweetComplianceStreamResponseOneOf1(value)) {
        return TweetComplianceStreamResponseOneOf1ToJSON(value as TweetComplianceStreamResponseOneOf1);
    }

    return {};
}

