/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TweetComplianceSchema } from './TweetComplianceSchema';
import {
    TweetComplianceSchemaFromJSON,
    TweetComplianceSchemaFromJSONTyped,
    TweetComplianceSchemaToJSON,
} from './TweetComplianceSchema';

/**
 * 
 * @export
 * @interface TweetDeleteComplianceSchema
 */
export interface TweetDeleteComplianceSchema {
    /**
     * 
     * @type {TweetComplianceSchema}
     * @memberof TweetDeleteComplianceSchema
     */
    _delete: TweetComplianceSchema;
}

/**
 * Check if a given object implements the TweetDeleteComplianceSchema interface.
 */
export function instanceOfTweetDeleteComplianceSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "_delete" in value;

    return isInstance;
}

export function TweetDeleteComplianceSchemaFromJSON(json: any): TweetDeleteComplianceSchema {
    return TweetDeleteComplianceSchemaFromJSONTyped(json, false);
}

export function TweetDeleteComplianceSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetDeleteComplianceSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_delete': TweetComplianceSchemaFromJSON(json['delete']),
    };
}

export function TweetDeleteComplianceSchemaToJSON(value?: TweetDeleteComplianceSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'delete': TweetComplianceSchemaToJSON(value._delete),
    };
}

