/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Promoted nonpublic engagement metrics for the Tweet at the time of the request.
 * @export
 * @interface TweetPromotedMetrics
 */
export interface TweetPromotedMetrics {
    /**
     * Number of times this Tweet has been viewed.
     * @type {number}
     * @memberof TweetPromotedMetrics
     */
    impressionCount?: number;
    /**
     * Number of times this Tweet has been liked.
     * @type {number}
     * @memberof TweetPromotedMetrics
     */
    likeCount?: number;
    /**
     * Number of times this Tweet has been replied to.
     * @type {number}
     * @memberof TweetPromotedMetrics
     */
    replyCount?: number;
    /**
     * Number of times this Tweet has been Retweeted.
     * @type {number}
     * @memberof TweetPromotedMetrics
     */
    retweetCount?: number;
}

/**
 * Check if a given object implements the TweetPromotedMetrics interface.
 */
export function instanceOfTweetPromotedMetrics(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TweetPromotedMetricsFromJSON(json: any): TweetPromotedMetrics {
    return TweetPromotedMetricsFromJSONTyped(json, false);
}

export function TweetPromotedMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetPromotedMetrics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'impressionCount': !exists(json, 'impression_count') ? undefined : json['impression_count'],
        'likeCount': !exists(json, 'like_count') ? undefined : json['like_count'],
        'replyCount': !exists(json, 'reply_count') ? undefined : json['reply_count'],
        'retweetCount': !exists(json, 'retweet_count') ? undefined : json['retweet_count'],
    };
}

export function TweetPromotedMetricsToJSON(value?: TweetPromotedMetrics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'impression_count': value.impressionCount,
        'like_count': value.likeCount,
        'reply_count': value.replyCount,
        'retweet_count': value.retweetCount,
    };
}

