/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TweetTakedownComplianceSchema } from './TweetTakedownComplianceSchema';
import {
    TweetTakedownComplianceSchemaFromJSON,
    TweetTakedownComplianceSchemaFromJSONTyped,
    TweetTakedownComplianceSchemaToJSON,
} from './TweetTakedownComplianceSchema';

/**
 * 
 * @export
 * @interface TweetWithheldComplianceSchema
 */
export interface TweetWithheldComplianceSchema {
    /**
     * 
     * @type {TweetTakedownComplianceSchema}
     * @memberof TweetWithheldComplianceSchema
     */
    withheld: TweetTakedownComplianceSchema;
}

/**
 * Check if a given object implements the TweetWithheldComplianceSchema interface.
 */
export function instanceOfTweetWithheldComplianceSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "withheld" in value;

    return isInstance;
}

export function TweetWithheldComplianceSchemaFromJSON(json: any): TweetWithheldComplianceSchema {
    return TweetWithheldComplianceSchemaFromJSONTyped(json, false);
}

export function TweetWithheldComplianceSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetWithheldComplianceSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'withheld': TweetTakedownComplianceSchemaFromJSON(json['withheld']),
    };
}

export function TweetWithheldComplianceSchemaToJSON(value?: TweetWithheldComplianceSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'withheld': TweetTakedownComplianceSchemaToJSON(value.withheld),
    };
}

