/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    TweetDeleteComplianceSchema,
    instanceOfTweetDeleteComplianceSchema,
    TweetDeleteComplianceSchemaFromJSON,
    TweetDeleteComplianceSchemaFromJSONTyped,
    TweetDeleteComplianceSchemaToJSON,
} from './TweetDeleteComplianceSchema';
import {
    TweetDropComplianceSchema,
    instanceOfTweetDropComplianceSchema,
    TweetDropComplianceSchemaFromJSON,
    TweetDropComplianceSchemaFromJSONTyped,
    TweetDropComplianceSchemaToJSON,
} from './TweetDropComplianceSchema';
import {
    TweetUndropComplianceSchema,
    instanceOfTweetUndropComplianceSchema,
    TweetUndropComplianceSchemaFromJSON,
    TweetUndropComplianceSchemaFromJSONTyped,
    TweetUndropComplianceSchemaToJSON,
} from './TweetUndropComplianceSchema';
import {
    TweetWithheldComplianceSchema,
    instanceOfTweetWithheldComplianceSchema,
    TweetWithheldComplianceSchemaFromJSON,
    TweetWithheldComplianceSchemaFromJSONTyped,
    TweetWithheldComplianceSchemaToJSON,
} from './TweetWithheldComplianceSchema';

/**
 * @type TweetComplianceData
 * Tweet compliance data.
 * @export
 */
export type TweetComplianceData = TweetDeleteComplianceSchema | TweetDropComplianceSchema | TweetUndropComplianceSchema | TweetWithheldComplianceSchema;

export function TweetComplianceDataFromJSON(json: any): TweetComplianceData {
    return TweetComplianceDataFromJSONTyped(json, false);
}

export function TweetComplianceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetComplianceData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...TweetDeleteComplianceSchemaFromJSONTyped(json, true), ...TweetDropComplianceSchemaFromJSONTyped(json, true), ...TweetUndropComplianceSchemaFromJSONTyped(json, true), ...TweetWithheldComplianceSchemaFromJSONTyped(json, true) };
}

export function TweetComplianceDataToJSON(value?: TweetComplianceData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfTweetDeleteComplianceSchema(value)) {
        return TweetDeleteComplianceSchemaToJSON(value as TweetDeleteComplianceSchema);
    }
    if (instanceOfTweetDropComplianceSchema(value)) {
        return TweetDropComplianceSchemaToJSON(value as TweetDropComplianceSchema);
    }
    if (instanceOfTweetUndropComplianceSchema(value)) {
        return TweetUndropComplianceSchemaToJSON(value as TweetUndropComplianceSchema);
    }
    if (instanceOfTweetWithheldComplianceSchema(value)) {
        return TweetWithheldComplianceSchemaToJSON(value as TweetWithheldComplianceSchema);
    }

    return {};
}

