/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TweetHideRequest
 */
export interface TweetHideRequest {
    /**
     * 
     * @type {boolean}
     * @memberof TweetHideRequest
     */
    hidden: boolean;
}

/**
 * Check if a given object implements the TweetHideRequest interface.
 */
export function instanceOfTweetHideRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "hidden" in value;

    return isInstance;
}

export function TweetHideRequestFromJSON(json: any): TweetHideRequest {
    return TweetHideRequestFromJSONTyped(json, false);
}

export function TweetHideRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetHideRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hidden': json['hidden'],
    };
}

export function TweetHideRequestToJSON(value?: TweetHideRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hidden': value.hidden,
    };
}

