/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';

/**
 * 
 * @export
 * @interface TweetComplianceStreamResponseOneOf1
 */
export interface TweetComplianceStreamResponseOneOf1 {
    /**
     * 
     * @type {Array<Problem>}
     * @memberof TweetComplianceStreamResponseOneOf1
     */
    errors: Array<Problem>;
}

/**
 * Check if a given object implements the TweetComplianceStreamResponseOneOf1 interface.
 */
export function instanceOfTweetComplianceStreamResponseOneOf1(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "errors" in value;

    return isInstance;
}

export function TweetComplianceStreamResponseOneOf1FromJSON(json: any): TweetComplianceStreamResponseOneOf1 {
    return TweetComplianceStreamResponseOneOf1FromJSONTyped(json, false);
}

export function TweetComplianceStreamResponseOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetComplianceStreamResponseOneOf1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errors': ((json['errors'] as Array<any>).map(ProblemFromJSON)),
    };
}

export function TweetComplianceStreamResponseOneOf1ToJSON(value?: TweetComplianceStreamResponseOneOf1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errors': ((value.errors as Array<any>).map(ProblemToJSON)),
    };
}

