/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Specifies the type of attachments (if any) present in this Tweet.
 * @export
 * @interface TweetAttachments
 */
export interface TweetAttachments {
    /**
     * A list of Media Keys for each one of the media attachments (if media are attached).
     * @type {Array<string>}
     * @memberof TweetAttachments
     */
    mediaKeys?: Array<string>;
    /**
     * A list of poll IDs (if polls are attached).
     * @type {Array<string>}
     * @memberof TweetAttachments
     */
    pollIds?: Array<string>;
}

/**
 * Check if a given object implements the TweetAttachments interface.
 */
export function instanceOfTweetAttachments(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TweetAttachmentsFromJSON(json: any): TweetAttachments {
    return TweetAttachmentsFromJSONTyped(json, false);
}

export function TweetAttachmentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetAttachments {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mediaKeys': !exists(json, 'media_keys') ? undefined : json['media_keys'],
        'pollIds': !exists(json, 'poll_ids') ? undefined : json['poll_ids'],
    };
}

export function TweetAttachmentsToJSON(value?: TweetAttachments | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'media_keys': value.mediaKeys,
        'poll_ids': value.pollIds,
    };
}

