/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';
import type { TweetDeleteResponseData } from './TweetDeleteResponseData';
import {
    TweetDeleteResponseDataFromJSON,
    TweetDeleteResponseDataFromJSONTyped,
    TweetDeleteResponseDataToJSON,
} from './TweetDeleteResponseData';

/**
 * 
 * @export
 * @interface TweetDeleteResponse
 */
export interface TweetDeleteResponse {
    /**
     * 
     * @type {TweetDeleteResponseData}
     * @memberof TweetDeleteResponse
     */
    data?: TweetDeleteResponseData;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof TweetDeleteResponse
     */
    errors?: Array<Problem>;
}

/**
 * Check if a given object implements the TweetDeleteResponse interface.
 */
export function instanceOfTweetDeleteResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TweetDeleteResponseFromJSON(json: any): TweetDeleteResponse {
    return TweetDeleteResponseFromJSONTyped(json, false);
}

export function TweetDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetDeleteResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : TweetDeleteResponseDataFromJSON(json['data']),
        'errors': !exists(json, 'errors') ? undefined : ((json['errors'] as Array<any>).map(ProblemFromJSON)),
    };
}

export function TweetDeleteResponseToJSON(value?: TweetDeleteResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': TweetDeleteResponseDataToJSON(value.data),
        'errors': value.errors === undefined ? undefined : ((value.errors as Array<any>).map(ProblemToJSON)),
    };
}

