/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';

/**
 * A problem that indicates that the authentication used is not supported.
 * @export
 * @interface UnsupportedAuthenticationProblem
 */
export interface UnsupportedAuthenticationProblem extends Problem {
}

/**
 * Check if a given object implements the UnsupportedAuthenticationProblem interface.
 */
export function instanceOfUnsupportedAuthenticationProblem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UnsupportedAuthenticationProblemFromJSON(json: any): UnsupportedAuthenticationProblem {
    return UnsupportedAuthenticationProblemFromJSONTyped(json, false);
}

export function UnsupportedAuthenticationProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnsupportedAuthenticationProblem {
    return json;
}

export function UnsupportedAuthenticationProblemToJSON(value?: UnsupportedAuthenticationProblem | null): any {
    return value;
}

