/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UrlImage } from './UrlImage';
import {
    UrlImageFromJSON,
    UrlImageFromJSONTyped,
    UrlImageToJSON,
} from './UrlImage';

/**
 * Represent the portion of text recognized as a URL.
 * @export
 * @interface UrlFields
 */
export interface UrlFields {
    /**
     * Description of the URL landing page.
     * @type {string}
     * @memberof UrlFields
     */
    description?: string;
    /**
     * The URL as displayed in the Twitter client.
     * @type {string}
     * @memberof UrlFields
     */
    displayUrl?: string;
    /**
     * A validly formatted URL.
     * @type {string}
     * @memberof UrlFields
     */
    expandedUrl?: string;
    /**
     * 
     * @type {Array<UrlImage>}
     * @memberof UrlFields
     */
    images?: Array<UrlImage>;
    /**
     * The Media Key identifier for this attachment.
     * @type {string}
     * @memberof UrlFields
     */
    mediaKey?: string;
    /**
     * HTTP Status Code.
     * @type {number}
     * @memberof UrlFields
     */
    status?: number;
    /**
     * Title of the page the URL points to.
     * @type {string}
     * @memberof UrlFields
     */
    title?: string;
    /**
     * Fully resolved url.
     * @type {string}
     * @memberof UrlFields
     */
    unwoundUrl?: string;
    /**
     * A validly formatted URL.
     * @type {string}
     * @memberof UrlFields
     */
    url: string;
}

/**
 * Check if a given object implements the UrlFields interface.
 */
export function instanceOfUrlFields(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function UrlFieldsFromJSON(json: any): UrlFields {
    return UrlFieldsFromJSONTyped(json, false);
}

export function UrlFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UrlFields {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'displayUrl': !exists(json, 'display_url') ? undefined : json['display_url'],
        'expandedUrl': !exists(json, 'expanded_url') ? undefined : json['expanded_url'],
        'images': !exists(json, 'images') ? undefined : ((json['images'] as Array<any>).map(UrlImageFromJSON)),
        'mediaKey': !exists(json, 'media_key') ? undefined : json['media_key'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'unwoundUrl': !exists(json, 'unwound_url') ? undefined : json['unwound_url'],
        'url': json['url'],
    };
}

export function UrlFieldsToJSON(value?: UrlFields | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'display_url': value.displayUrl,
        'expanded_url': value.expandedUrl,
        'images': value.images === undefined ? undefined : ((value.images as Array<any>).map(UrlImageToJSON)),
        'media_key': value.mediaKey,
        'status': value.status,
        'title': value.title,
        'unwound_url': value.unwoundUrl,
        'url': value.url,
    };
}

