/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserTakedownComplianceSchema } from './UserTakedownComplianceSchema';
import {
    UserTakedownComplianceSchemaFromJSON,
    UserTakedownComplianceSchemaFromJSONTyped,
    UserTakedownComplianceSchemaToJSON,
} from './UserTakedownComplianceSchema';

/**
 * 
 * @export
 * @interface UserWithheldComplianceSchema
 */
export interface UserWithheldComplianceSchema {
    /**
     * 
     * @type {UserTakedownComplianceSchema}
     * @memberof UserWithheldComplianceSchema
     */
    userWithheld: UserTakedownComplianceSchema;
}

/**
 * Check if a given object implements the UserWithheldComplianceSchema interface.
 */
export function instanceOfUserWithheldComplianceSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userWithheld" in value;

    return isInstance;
}

export function UserWithheldComplianceSchemaFromJSON(json: any): UserWithheldComplianceSchema {
    return UserWithheldComplianceSchemaFromJSONTyped(json, false);
}

export function UserWithheldComplianceSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWithheldComplianceSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userWithheld': UserTakedownComplianceSchemaFromJSON(json['user_withheld']),
    };
}

export function UserWithheldComplianceSchemaToJSON(value?: UserWithheldComplianceSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_withheld': UserTakedownComplianceSchemaToJSON(value.userWithheld),
    };
}

