/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserComplianceSchemaUser } from './UserComplianceSchemaUser';
import {
    UserComplianceSchemaUserFromJSON,
    UserComplianceSchemaUserFromJSONTyped,
    UserComplianceSchemaUserToJSON,
} from './UserComplianceSchemaUser';

/**
 * 
 * @export
 * @interface UserProfileModificationObjectSchema
 */
export interface UserProfileModificationObjectSchema {
    /**
     * Event time.
     * @type {Date}
     * @memberof UserProfileModificationObjectSchema
     */
    eventAt: Date;
    /**
     * 
     * @type {string}
     * @memberof UserProfileModificationObjectSchema
     */
    newValue: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileModificationObjectSchema
     */
    profileField: string;
    /**
     * 
     * @type {UserComplianceSchemaUser}
     * @memberof UserProfileModificationObjectSchema
     */
    user: UserComplianceSchemaUser;
}

/**
 * Check if a given object implements the UserProfileModificationObjectSchema interface.
 */
export function instanceOfUserProfileModificationObjectSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "eventAt" in value;
    isInstance = isInstance && "newValue" in value;
    isInstance = isInstance && "profileField" in value;
    isInstance = isInstance && "user" in value;

    return isInstance;
}

export function UserProfileModificationObjectSchemaFromJSON(json: any): UserProfileModificationObjectSchema {
    return UserProfileModificationObjectSchemaFromJSONTyped(json, false);
}

export function UserProfileModificationObjectSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileModificationObjectSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eventAt': (new Date(json['event_at'])),
        'newValue': json['new_value'],
        'profileField': json['profile_field'],
        'user': UserComplianceSchemaUserFromJSON(json['user']),
    };
}

export function UserProfileModificationObjectSchemaToJSON(value?: UserProfileModificationObjectSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'event_at': (value.eventAt.toISOString()),
        'new_value': value.newValue,
        'profile_field': value.profileField,
        'user': UserComplianceSchemaUserToJSON(value.user),
    };
}

