/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserComplianceSchema } from './UserComplianceSchema';
import {
    UserComplianceSchemaFromJSON,
    UserComplianceSchemaFromJSONTyped,
    UserComplianceSchemaToJSON,
} from './UserComplianceSchema';

/**
 * 
 * @export
 * @interface UserUndeleteComplianceSchema
 */
export interface UserUndeleteComplianceSchema {
    /**
     * 
     * @type {UserComplianceSchema}
     * @memberof UserUndeleteComplianceSchema
     */
    userUndelete: UserComplianceSchema;
}

/**
 * Check if a given object implements the UserUndeleteComplianceSchema interface.
 */
export function instanceOfUserUndeleteComplianceSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userUndelete" in value;

    return isInstance;
}

export function UserUndeleteComplianceSchemaFromJSON(json: any): UserUndeleteComplianceSchema {
    return UserUndeleteComplianceSchemaFromJSONTyped(json, false);
}

export function UserUndeleteComplianceSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUndeleteComplianceSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userUndelete': UserComplianceSchemaFromJSON(json['user_undelete']),
    };
}

export function UserUndeleteComplianceSchemaToJSON(value?: UserUndeleteComplianceSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_undelete': UserComplianceSchemaToJSON(value.userUndelete),
    };
}

