/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    UserDeleteComplianceSchema,
    instanceOfUserDeleteComplianceSchema,
    UserDeleteComplianceSchemaFromJSON,
    UserDeleteComplianceSchemaFromJSONTyped,
    UserDeleteComplianceSchemaToJSON,
} from './UserDeleteComplianceSchema';
import {
    UserProfileModificationComplianceSchema,
    instanceOfUserProfileModificationComplianceSchema,
    UserProfileModificationComplianceSchemaFromJSON,
    UserProfileModificationComplianceSchemaFromJSONTyped,
    UserProfileModificationComplianceSchemaToJSON,
} from './UserProfileModificationComplianceSchema';
import {
    UserProtectComplianceSchema,
    instanceOfUserProtectComplianceSchema,
    UserProtectComplianceSchemaFromJSON,
    UserProtectComplianceSchemaFromJSONTyped,
    UserProtectComplianceSchemaToJSON,
} from './UserProtectComplianceSchema';
import {
    UserScrubGeoSchema,
    instanceOfUserScrubGeoSchema,
    UserScrubGeoSchemaFromJSON,
    UserScrubGeoSchemaFromJSONTyped,
    UserScrubGeoSchemaToJSON,
} from './UserScrubGeoSchema';
import {
    UserSuspendComplianceSchema,
    instanceOfUserSuspendComplianceSchema,
    UserSuspendComplianceSchemaFromJSON,
    UserSuspendComplianceSchemaFromJSONTyped,
    UserSuspendComplianceSchemaToJSON,
} from './UserSuspendComplianceSchema';
import {
    UserUndeleteComplianceSchema,
    instanceOfUserUndeleteComplianceSchema,
    UserUndeleteComplianceSchemaFromJSON,
    UserUndeleteComplianceSchemaFromJSONTyped,
    UserUndeleteComplianceSchemaToJSON,
} from './UserUndeleteComplianceSchema';
import {
    UserUnprotectComplianceSchema,
    instanceOfUserUnprotectComplianceSchema,
    UserUnprotectComplianceSchemaFromJSON,
    UserUnprotectComplianceSchemaFromJSONTyped,
    UserUnprotectComplianceSchemaToJSON,
} from './UserUnprotectComplianceSchema';
import {
    UserUnsuspendComplianceSchema,
    instanceOfUserUnsuspendComplianceSchema,
    UserUnsuspendComplianceSchemaFromJSON,
    UserUnsuspendComplianceSchemaFromJSONTyped,
    UserUnsuspendComplianceSchemaToJSON,
} from './UserUnsuspendComplianceSchema';
import {
    UserWithheldComplianceSchema,
    instanceOfUserWithheldComplianceSchema,
    UserWithheldComplianceSchemaFromJSON,
    UserWithheldComplianceSchemaFromJSONTyped,
    UserWithheldComplianceSchemaToJSON,
} from './UserWithheldComplianceSchema';

/**
 * @type UserComplianceData
 * User compliance data.
 * @export
 */
export type UserComplianceData = UserDeleteComplianceSchema | UserProfileModificationComplianceSchema | UserProtectComplianceSchema | UserScrubGeoSchema | UserSuspendComplianceSchema | UserUndeleteComplianceSchema | UserUnprotectComplianceSchema | UserUnsuspendComplianceSchema | UserWithheldComplianceSchema;

export function UserComplianceDataFromJSON(json: any): UserComplianceData {
    return UserComplianceDataFromJSONTyped(json, false);
}

export function UserComplianceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserComplianceData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...UserDeleteComplianceSchemaFromJSONTyped(json, true), ...UserProfileModificationComplianceSchemaFromJSONTyped(json, true), ...UserProtectComplianceSchemaFromJSONTyped(json, true), ...UserScrubGeoSchemaFromJSONTyped(json, true), ...UserSuspendComplianceSchemaFromJSONTyped(json, true), ...UserUndeleteComplianceSchemaFromJSONTyped(json, true), ...UserUnprotectComplianceSchemaFromJSONTyped(json, true), ...UserUnsuspendComplianceSchemaFromJSONTyped(json, true), ...UserWithheldComplianceSchemaFromJSONTyped(json, true) };
}

export function UserComplianceDataToJSON(value?: UserComplianceData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfUserDeleteComplianceSchema(value)) {
        return UserDeleteComplianceSchemaToJSON(value as UserDeleteComplianceSchema);
    }
    if (instanceOfUserProfileModificationComplianceSchema(value)) {
        return UserProfileModificationComplianceSchemaToJSON(value as UserProfileModificationComplianceSchema);
    }
    if (instanceOfUserProtectComplianceSchema(value)) {
        return UserProtectComplianceSchemaToJSON(value as UserProtectComplianceSchema);
    }
    if (instanceOfUserScrubGeoSchema(value)) {
        return UserScrubGeoSchemaToJSON(value as UserScrubGeoSchema);
    }
    if (instanceOfUserSuspendComplianceSchema(value)) {
        return UserSuspendComplianceSchemaToJSON(value as UserSuspendComplianceSchema);
    }
    if (instanceOfUserUndeleteComplianceSchema(value)) {
        return UserUndeleteComplianceSchemaToJSON(value as UserUndeleteComplianceSchema);
    }
    if (instanceOfUserUnprotectComplianceSchema(value)) {
        return UserUnprotectComplianceSchemaToJSON(value as UserUnprotectComplianceSchema);
    }
    if (instanceOfUserUnsuspendComplianceSchema(value)) {
        return UserUnsuspendComplianceSchemaToJSON(value as UserUnsuspendComplianceSchema);
    }
    if (instanceOfUserWithheldComplianceSchema(value)) {
        return UserWithheldComplianceSchemaToJSON(value as UserWithheldComplianceSchema);
    }

    return {};
}

