/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    TweetComplianceStreamResponseOneOf1,
    instanceOfTweetComplianceStreamResponseOneOf1,
    TweetComplianceStreamResponseOneOf1FromJSON,
    TweetComplianceStreamResponseOneOf1FromJSONTyped,
    TweetComplianceStreamResponseOneOf1ToJSON,
} from './TweetComplianceStreamResponseOneOf1';
import {
    UserComplianceStreamResponseOneOf,
    instanceOfUserComplianceStreamResponseOneOf,
    UserComplianceStreamResponseOneOfFromJSON,
    UserComplianceStreamResponseOneOfFromJSONTyped,
    UserComplianceStreamResponseOneOfToJSON,
} from './UserComplianceStreamResponseOneOf';

/**
 * @type UserComplianceStreamResponse
 * User compliance stream events.
 * @export
 */
export type UserComplianceStreamResponse = TweetComplianceStreamResponseOneOf1 | UserComplianceStreamResponseOneOf;

export function UserComplianceStreamResponseFromJSON(json: any): UserComplianceStreamResponse {
    return UserComplianceStreamResponseFromJSONTyped(json, false);
}

export function UserComplianceStreamResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserComplianceStreamResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...TweetComplianceStreamResponseOneOf1FromJSONTyped(json, true), ...UserComplianceStreamResponseOneOfFromJSONTyped(json, true) };
}

export function UserComplianceStreamResponseToJSON(value?: UserComplianceStreamResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfTweetComplianceStreamResponseOneOf1(value)) {
        return TweetComplianceStreamResponseOneOf1ToJSON(value as TweetComplianceStreamResponseOneOf1);
    }
    if (instanceOfUserComplianceStreamResponseOneOf(value)) {
        return UserComplianceStreamResponseOneOfToJSON(value as UserComplianceStreamResponseOneOf);
    }

    return {};
}

