/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersLikesCreateResponseData
 */
export interface UsersLikesCreateResponseData {
    /**
     * 
     * @type {boolean}
     * @memberof UsersLikesCreateResponseData
     */
    liked?: boolean;
}

/**
 * Check if a given object implements the UsersLikesCreateResponseData interface.
 */
export function instanceOfUsersLikesCreateResponseData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersLikesCreateResponseDataFromJSON(json: any): UsersLikesCreateResponseData {
    return UsersLikesCreateResponseDataFromJSONTyped(json, false);
}

export function UsersLikesCreateResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersLikesCreateResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'liked': !exists(json, 'liked') ? undefined : json['liked'],
    };
}

export function UsersLikesCreateResponseDataToJSON(value?: UsersLikesCreateResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'liked': value.liked,
    };
}

