/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserComplianceSchemaUser } from './UserComplianceSchemaUser';
import {
    UserComplianceSchemaUserFromJSON,
    UserComplianceSchemaUserFromJSONTyped,
    UserComplianceSchemaUserToJSON,
} from './UserComplianceSchemaUser';

/**
 * 
 * @export
 * @interface UserTakedownComplianceSchema
 */
export interface UserTakedownComplianceSchema {
    /**
     * Event time.
     * @type {Date}
     * @memberof UserTakedownComplianceSchema
     */
    eventAt: Date;
    /**
     * 
     * @type {UserComplianceSchemaUser}
     * @memberof UserTakedownComplianceSchema
     */
    user: UserComplianceSchemaUser;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserTakedownComplianceSchema
     */
    withheldInCountries: Array<string>;
}

/**
 * Check if a given object implements the UserTakedownComplianceSchema interface.
 */
export function instanceOfUserTakedownComplianceSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "eventAt" in value;
    isInstance = isInstance && "user" in value;
    isInstance = isInstance && "withheldInCountries" in value;

    return isInstance;
}

export function UserTakedownComplianceSchemaFromJSON(json: any): UserTakedownComplianceSchema {
    return UserTakedownComplianceSchemaFromJSONTyped(json, false);
}

export function UserTakedownComplianceSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserTakedownComplianceSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eventAt': (new Date(json['event_at'])),
        'user': UserComplianceSchemaUserFromJSON(json['user']),
        'withheldInCountries': json['withheld_in_countries'],
    };
}

export function UserTakedownComplianceSchemaToJSON(value?: UserTakedownComplianceSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'event_at': (value.eventAt.toISOString()),
        'user': UserComplianceSchemaUserToJSON(value.user),
        'withheld_in_countries': value.withheldInCountries,
    };
}

