/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersFollowingCreateRequest
 */
export interface UsersFollowingCreateRequest {
    /**
     * Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
     * @type {string}
     * @memberof UsersFollowingCreateRequest
     */
    targetUserId: string;
}

/**
 * Check if a given object implements the UsersFollowingCreateRequest interface.
 */
export function instanceOfUsersFollowingCreateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "targetUserId" in value;

    return isInstance;
}

export function UsersFollowingCreateRequestFromJSON(json: any): UsersFollowingCreateRequest {
    return UsersFollowingCreateRequestFromJSONTyped(json, false);
}

export function UsersFollowingCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersFollowingCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'targetUserId': json['target_user_id'],
    };
}

export function UsersFollowingCreateRequestToJSON(value?: UsersFollowingCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'target_user_id': value.targetUserId,
    };
}

