/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserComplianceSchemaUser
 */
export interface UserComplianceSchemaUser {
    /**
     * Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
     * @type {string}
     * @memberof UserComplianceSchemaUser
     */
    id: string;
}

/**
 * Check if a given object implements the UserComplianceSchemaUser interface.
 */
export function instanceOfUserComplianceSchemaUser(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function UserComplianceSchemaUserFromJSON(json: any): UserComplianceSchemaUser {
    return UserComplianceSchemaUserFromJSONTyped(json, false);
}

export function UserComplianceSchemaUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserComplianceSchemaUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function UserComplianceSchemaUserToJSON(value?: UserComplianceSchemaUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

