/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ListFollowedResponseData } from './ListFollowedResponseData';
import {
    ListFollowedResponseDataFromJSON,
    ListFollowedResponseDataFromJSONTyped,
    ListFollowedResponseDataToJSON,
} from './ListFollowedResponseData';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';

/**
 * 
 * @export
 * @interface UsersFollowingDeleteResponse
 */
export interface UsersFollowingDeleteResponse {
    /**
     * 
     * @type {ListFollowedResponseData}
     * @memberof UsersFollowingDeleteResponse
     */
    data?: ListFollowedResponseData;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof UsersFollowingDeleteResponse
     */
    errors?: Array<Problem>;
}

/**
 * Check if a given object implements the UsersFollowingDeleteResponse interface.
 */
export function instanceOfUsersFollowingDeleteResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersFollowingDeleteResponseFromJSON(json: any): UsersFollowingDeleteResponse {
    return UsersFollowingDeleteResponseFromJSONTyped(json, false);
}

export function UsersFollowingDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersFollowingDeleteResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ListFollowedResponseDataFromJSON(json['data']),
        'errors': !exists(json, 'errors') ? undefined : ((json['errors'] as Array<any>).map(ProblemFromJSON)),
    };
}

export function UsersFollowingDeleteResponseToJSON(value?: UsersFollowingDeleteResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ListFollowedResponseDataToJSON(value.data),
        'errors': value.errors === undefined ? undefined : ((value.errors as Array<any>).map(ProblemToJSON)),
    };
}

