/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Problem } from './Problem';
import {
    ProblemFromJSON,
    ProblemFromJSONTyped,
    ProblemToJSON,
} from './Problem';
import type { UsersLikesCreateResponseData } from './UsersLikesCreateResponseData';
import {
    UsersLikesCreateResponseDataFromJSON,
    UsersLikesCreateResponseDataFromJSONTyped,
    UsersLikesCreateResponseDataToJSON,
} from './UsersLikesCreateResponseData';

/**
 * 
 * @export
 * @interface UsersLikesDeleteResponse
 */
export interface UsersLikesDeleteResponse {
    /**
     * 
     * @type {UsersLikesCreateResponseData}
     * @memberof UsersLikesDeleteResponse
     */
    data?: UsersLikesCreateResponseData;
    /**
     * 
     * @type {Array<Problem>}
     * @memberof UsersLikesDeleteResponse
     */
    errors?: Array<Problem>;
}

/**
 * Check if a given object implements the UsersLikesDeleteResponse interface.
 */
export function instanceOfUsersLikesDeleteResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersLikesDeleteResponseFromJSON(json: any): UsersLikesDeleteResponse {
    return UsersLikesDeleteResponseFromJSONTyped(json, false);
}

export function UsersLikesDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersLikesDeleteResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : UsersLikesCreateResponseDataFromJSON(json['data']),
        'errors': !exists(json, 'errors') ? undefined : ((json['errors'] as Array<any>).map(ProblemFromJSON)),
    };
}

export function UsersLikesDeleteResponseToJSON(value?: UsersLikesDeleteResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': UsersLikesCreateResponseDataToJSON(value.data),
        'errors': value.errors === undefined ? undefined : ((value.errors as Array<any>).map(ProblemToJSON)),
    };
}

