/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Variant } from './Variant';
import {
    VariantFromJSON,
    VariantFromJSONTyped,
    VariantToJSON,
} from './Variant';
import type { VideoAllOfNonPublicMetrics } from './VideoAllOfNonPublicMetrics';
import {
    VideoAllOfNonPublicMetricsFromJSON,
    VideoAllOfNonPublicMetricsFromJSONTyped,
    VideoAllOfNonPublicMetricsToJSON,
} from './VideoAllOfNonPublicMetrics';
import type { VideoAllOfOrganicMetrics } from './VideoAllOfOrganicMetrics';
import {
    VideoAllOfOrganicMetricsFromJSON,
    VideoAllOfOrganicMetricsFromJSONTyped,
    VideoAllOfOrganicMetricsToJSON,
} from './VideoAllOfOrganicMetrics';
import type { VideoAllOfPromotedMetrics } from './VideoAllOfPromotedMetrics';
import {
    VideoAllOfPromotedMetricsFromJSON,
    VideoAllOfPromotedMetricsFromJSONTyped,
    VideoAllOfPromotedMetricsToJSON,
} from './VideoAllOfPromotedMetrics';
import type { VideoAllOfPublicMetrics } from './VideoAllOfPublicMetrics';
import {
    VideoAllOfPublicMetricsFromJSON,
    VideoAllOfPublicMetricsFromJSONTyped,
    VideoAllOfPublicMetricsToJSON,
} from './VideoAllOfPublicMetrics';

/**
 * 
 * @export
 * @interface VideoAllOf
 */
export interface VideoAllOf {
    /**
     * 
     * @type {number}
     * @memberof VideoAllOf
     */
    durationMs?: number;
    /**
     * 
     * @type {VideoAllOfNonPublicMetrics}
     * @memberof VideoAllOf
     */
    nonPublicMetrics?: VideoAllOfNonPublicMetrics;
    /**
     * 
     * @type {VideoAllOfOrganicMetrics}
     * @memberof VideoAllOf
     */
    organicMetrics?: VideoAllOfOrganicMetrics;
    /**
     * 
     * @type {string}
     * @memberof VideoAllOf
     */
    previewImageUrl?: string;
    /**
     * 
     * @type {VideoAllOfPromotedMetrics}
     * @memberof VideoAllOf
     */
    promotedMetrics?: VideoAllOfPromotedMetrics;
    /**
     * 
     * @type {VideoAllOfPublicMetrics}
     * @memberof VideoAllOf
     */
    publicMetrics?: VideoAllOfPublicMetrics;
    /**
     * An array of all available variants of the media.
     * @type {Array<Variant>}
     * @memberof VideoAllOf
     */
    variants?: Array<Variant>;
}

/**
 * Check if a given object implements the VideoAllOf interface.
 */
export function instanceOfVideoAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VideoAllOfFromJSON(json: any): VideoAllOf {
    return VideoAllOfFromJSONTyped(json, false);
}

export function VideoAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'durationMs': !exists(json, 'duration_ms') ? undefined : json['duration_ms'],
        'nonPublicMetrics': !exists(json, 'non_public_metrics') ? undefined : VideoAllOfNonPublicMetricsFromJSON(json['non_public_metrics']),
        'organicMetrics': !exists(json, 'organic_metrics') ? undefined : VideoAllOfOrganicMetricsFromJSON(json['organic_metrics']),
        'previewImageUrl': !exists(json, 'preview_image_url') ? undefined : json['preview_image_url'],
        'promotedMetrics': !exists(json, 'promoted_metrics') ? undefined : VideoAllOfPromotedMetricsFromJSON(json['promoted_metrics']),
        'publicMetrics': !exists(json, 'public_metrics') ? undefined : VideoAllOfPublicMetricsFromJSON(json['public_metrics']),
        'variants': !exists(json, 'variants') ? undefined : ((json['variants'] as Array<any>).map(VariantFromJSON)),
    };
}

export function VideoAllOfToJSON(value?: VideoAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'duration_ms': value.durationMs,
        'non_public_metrics': VideoAllOfNonPublicMetricsToJSON(value.nonPublicMetrics),
        'organic_metrics': VideoAllOfOrganicMetricsToJSON(value.organicMetrics),
        'preview_image_url': value.previewImageUrl,
        'promoted_metrics': VideoAllOfPromotedMetricsToJSON(value.promotedMetrics),
        'public_metrics': VideoAllOfPublicMetricsToJSON(value.publicMetrics),
        'variants': value.variants === undefined ? undefined : ((value.variants as Array<any>).map(VariantToJSON)),
    };
}

