/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Nonpublic engagement metrics for the Media at the time of the request.
 * @export
 * @interface VideoAllOfNonPublicMetrics
 */
export interface VideoAllOfNonPublicMetrics {
    /**
     * Number of users who made it through 0% of the video.
     * @type {number}
     * @memberof VideoAllOfNonPublicMetrics
     */
    playback0Count?: number;
    /**
     * Number of users who made it through 100% of the video.
     * @type {number}
     * @memberof VideoAllOfNonPublicMetrics
     */
    playback100Count?: number;
    /**
     * Number of users who made it through 25% of the video.
     * @type {number}
     * @memberof VideoAllOfNonPublicMetrics
     */
    playback25Count?: number;
    /**
     * Number of users who made it through 50% of the video.
     * @type {number}
     * @memberof VideoAllOfNonPublicMetrics
     */
    playback50Count?: number;
    /**
     * Number of users who made it through 75% of the video.
     * @type {number}
     * @memberof VideoAllOfNonPublicMetrics
     */
    playback75Count?: number;
}

/**
 * Check if a given object implements the VideoAllOfNonPublicMetrics interface.
 */
export function instanceOfVideoAllOfNonPublicMetrics(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VideoAllOfNonPublicMetricsFromJSON(json: any): VideoAllOfNonPublicMetrics {
    return VideoAllOfNonPublicMetricsFromJSONTyped(json, false);
}

export function VideoAllOfNonPublicMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoAllOfNonPublicMetrics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'playback0Count': !exists(json, 'playback_0_count') ? undefined : json['playback_0_count'],
        'playback100Count': !exists(json, 'playback_100_count') ? undefined : json['playback_100_count'],
        'playback25Count': !exists(json, 'playback_25_count') ? undefined : json['playback_25_count'],
        'playback50Count': !exists(json, 'playback_50_count') ? undefined : json['playback_50_count'],
        'playback75Count': !exists(json, 'playback_75_count') ? undefined : json['playback_75_count'],
    };
}

export function VideoAllOfNonPublicMetricsToJSON(value?: VideoAllOfNonPublicMetrics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'playback_0_count': value.playback0Count,
        'playback_100_count': value.playback100Count,
        'playback_25_count': value.playback25Count,
        'playback_50_count': value.playback50Count,
        'playback_75_count': value.playback75Count,
    };
}

