/* tslint:disable */
/* eslint-disable */
/**
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Engagement metrics for the Media at the time of the request.
 * @export
 * @interface VideoAllOfPublicMetrics
 */
export interface VideoAllOfPublicMetrics {
    /**
     * Number of times this video has been viewed.
     * @type {number}
     * @memberof VideoAllOfPublicMetrics
     */
    viewCount?: number;
}

/**
 * Check if a given object implements the VideoAllOfPublicMetrics interface.
 */
export function instanceOfVideoAllOfPublicMetrics(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VideoAllOfPublicMetricsFromJSON(json: any): VideoAllOfPublicMetrics {
    return VideoAllOfPublicMetricsFromJSONTyped(json, false);
}

export function VideoAllOfPublicMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoAllOfPublicMetrics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'viewCount': !exists(json, 'view_count') ? undefined : json['view_count'],
    };
}

export function VideoAllOfPublicMetricsToJSON(value?: VideoAllOfPublicMetrics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'view_count': value.viewCount,
    };
}

